# Step 1: Set the name of the file to work with

This should be the name of the directory created in Step 1 of `s1.process_ocr.ipynb`.

In [1]:
name = "ribier_v1"

# Step 2: Run the following Cell to generate embeddings for the OCR results

In [2]:
import polars as pl

dir = f"books_work/{name}/data/"
df = pl.read_parquet(f"{dir}{name}.parquet")

df = df.with_row_index("id", offset=10000)
df.head()

shape: (5, 5)
┌───────┬──────────────────────────┬────────────────┬────────────────────┬─────────────────────────┐
│ id    ┆ title                    ┆ pdf_pages      ┆ book_pages         ┆ markdown                │
│ ---   ┆ ---                      ┆ ---            ┆ ---                ┆ ---                     │
│ u32   ┆ str                      ┆ list[i64]      ┆ list[str]          ┆ str                     │
╞═══════╪══════════════════════════╪════════════════╪════════════════════╪═════════════════════════╡
│ 10000 ┆ CONTENANS                ┆ [4]            ┆ []                 ┆                         │
│       ┆                          ┆                ┆                    ┆                         │
│       ┆                          ┆                ┆                    ┆ LES INTELLIGENCES DE    │
│       ┆                          ┆                ┆                    ┆ CES ROY…                │
│ 10001 ┆ ET                       ┆ [4, 5, … 16]   ┆ ["10", "3", … "7"] ┆                         │
│       ┆                          ┆                ┆                    ┆                         │
│       ┆                          ┆                ┆                    ┆ DANS L'ITALIE SEVLE,    │
│       ┆                          ┆                ┆                    ┆ LES INT…                │
│ 10002 ┆ SVR LA PIECE SVIVANTE,   ┆ [16]           ┆ ["3"]              ┆                         │
│       ┆                          ┆                ┆                    ┆                         │
│       ┆                          ┆                ┆                    ┆                         │
│ 10003 ┆ ET AVTRES DV PREMIER     ┆ [16]           ┆ ["3"]              ┆                         │
│       ┆ LIVRE                    ┆                ┆                    ┆                         │
│       ┆                          ┆                ┆                    ┆                         │
│ 10004 ┆ DE CE RECEVIL            ┆ [16, 17, … 24] ┆ ["3", "6", … "1"]  ┆                         │
│       ┆                          ┆                ┆                    ┆                         │
│       ┆                          ┆                ┆                    ┆ ![img-6.jpeg](img-6.jpe │
│       ┆                          ┆                ┆                    ┆ g)                      │
│       ┆                          ┆                ┆                    ┆                         │
│       ┆                          ┆                ┆                    ┆ E…                      │
└───────┴──────────────────────────┴────────────────┴────────────────────┴─────────────────────────┘

In [3]:
from embeds.embed_letters import chunk_and_tokenize_letters

df = chunk_and_tokenize_letters(df)
df.sample(5)
df.write_parquet(f"{dir}{name}_chunked.parquet")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/74 [00:00<?, ?it/s]

Starting chunking and tokenization...
*************************
Completed chunking and tokenization in 0.16 seconds.

Batches:   0%|          | 0/207 [00:00<?, ?it/s]

*************************
Start Embedding Process, using the ibm-granite/granite-embedding-97m-multilingual-r2 model...
*************************
Completed embedding process in 0.03 seconds.

In [4]:
df.head()

shape: (5, 10)
┌───────────┬───────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ letter_id ┆ id    ┆ title      ┆ pdf_pages  ┆ … ┆ chunk_id ┆ word_lengt ┆ full_markd ┆ embedding │
│ ---       ┆ ---   ┆ ---        ┆ ---        ┆   ┆ ---      ┆ h          ┆ own        ┆ ---       │
│ u32       ┆ u32   ┆ str        ┆ list[i64]  ┆   ┆ f64      ┆ ---        ┆ ---        ┆ list[f64] │
│           ┆       ┆            ┆            ┆   ┆          ┆ i64        ┆ str        ┆           │
╞═══════════╪═══════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 10000     ┆ 10000 ┆ CONTENANS  ┆ [4]        ┆ … ┆ 10000.0  ┆ 41         ┆            ┆ [-0.02758 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ 8,        │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ LES INTELL ┆ 0.020996, │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ IGENCES DE ┆ … -0.036… │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ CES ROY…   ┆           │
│ 10001     ┆ 10001 ┆ ET         ┆ [4, 5, …   ┆ … ┆ 10001.0  ┆ 1972       ┆            ┆ [-0.04687 │
│           ┆       ┆            ┆ 16]        ┆   ┆          ┆            ┆            ┆ 5, -0.020 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ DANS       ┆ 142, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ L'ITALIE   ┆ -0.00…    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ SEVLE, LES ┆           │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ INT…       ┆           │
│ 10001     ┆ 10001 ┆ ET         ┆ [4, 5, …   ┆ … ┆ 10001.1  ┆ 1660       ┆            ┆ [-0.04638 │
│           ┆       ┆            ┆ 16]        ┆   ┆          ┆            ┆            ┆ 7, -0.040 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ DANS       ┆ 771, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ L'ITALIE   ┆ 0.015…    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ SEVLE, LES ┆           │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ INT…       ┆           │
│ 10002     ┆ 10002 ┆ SVR LA     ┆ [16]       ┆ … ┆ 10002.0  ┆ 0          ┆            ┆ [-0.04858 │
│           ┆       ┆ PIECE      ┆            ┆   ┆          ┆            ┆            ┆ 4, -0.026 │
│           ┆       ┆ SVIVANTE,  ┆            ┆   ┆          ┆            ┆            ┆ 123, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ -0.03…    │
│ 10003     ┆ 10003 ┆ ET AVTRES  ┆ [16]       ┆ … ┆ 10003.0  ┆ 0          ┆            ┆ [-0.04858 │
│           ┆       ┆ DV PREMIER ┆            ┆   ┆          ┆            ┆            ┆ 4, -0.026 │
│           ┆       ┆ LIVRE      ┆            ┆   ┆          ┆            ┆            ┆ 123, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ -0.03…    │
└───────────┴───────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘