In [ ]:
from pathlib import Path

import polars as pl
from clustering.clustering import create_cluster

name = "ribier_v1"
path = Path(f"books_work/{name}/data/{name}_chunked.parquet")

df = pl.read_parquet(path)
df.head()

shape: (5, 10)
┌───────────┬───────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ letter_id ┆ id    ┆ title      ┆ pdf_pages  ┆ … ┆ chunk_id ┆ word_lengt ┆ full_markd ┆ embedding │
│ ---       ┆ ---   ┆ ---        ┆ ---        ┆   ┆ ---      ┆ h          ┆ own        ┆ ---       │
│ u32       ┆ u32   ┆ str        ┆ list[i64]  ┆   ┆ f64      ┆ ---        ┆ ---        ┆ list[f64] │
│           ┆       ┆            ┆            ┆   ┆          ┆ i64        ┆ str        ┆           │
╞═══════════╪═══════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 10000     ┆ 10000 ┆ CONTENANS  ┆ [4]        ┆ … ┆ 10000.0  ┆ 41         ┆            ┆ [-0.02758 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ 8,        │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ LES INTELL ┆ 0.020996, │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ IGENCES DE ┆ … -0.036… │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ CES ROY…   ┆           │
│ 10001     ┆ 10001 ┆ ET         ┆ [4, 5, …   ┆ … ┆ 10001.0  ┆ 1972       ┆            ┆ [-0.04687 │
│           ┆       ┆            ┆ 16]        ┆   ┆          ┆            ┆            ┆ 5, -0.020 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ DANS       ┆ 142, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ L'ITALIE   ┆ -0.00…    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ SEVLE, LES ┆           │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ INT…       ┆           │
│ 10001     ┆ 10001 ┆ ET         ┆ [4, 5, …   ┆ … ┆ 10001.1  ┆ 1660       ┆            ┆ [-0.04638 │
│           ┆       ┆            ┆ 16]        ┆   ┆          ┆            ┆            ┆ 7, -0.040 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ DANS       ┆ 771, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ L'ITALIE   ┆ 0.015…    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ SEVLE, LES ┆           │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ INT…       ┆           │
│ 10002     ┆ 10002 ┆ SVR LA     ┆ [16]       ┆ … ┆ 10002.0  ┆ 0          ┆            ┆ [-0.04858 │
│           ┆       ┆ PIECE      ┆            ┆   ┆          ┆            ┆            ┆ 4, -0.026 │
│           ┆       ┆ SVIVANTE,  ┆            ┆   ┆          ┆            ┆            ┆ 123, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ -0.03…    │
│ 10003     ┆ 10003 ┆ ET AVTRES  ┆ [16]       ┆ … ┆ 10003.0  ┆ 0          ┆            ┆ [-0.04858 │
│           ┆       ┆ DV PREMIER ┆            ┆   ┆          ┆            ┆            ┆ 4, -0.026 │
│           ┆       ┆ LIVRE      ┆            ┆   ┆          ┆            ┆            ┆ 123, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ -0.03…    │
└───────────┴───────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [ ]:
embed_list = df["embedding"].to_list()
clusters, soft, samples, iters = create_cluster(embed_list)
clusters

  Estimated number of clusters: 14
  Restart 1/10 — score: 0.9358
  Restart 2/10 — score: 0.9360
  Restart 3/10 — score: 0.9360
  Restart 4/10 — score: 0.9354
  Restart 5/10 — score: 0.9371
  Restart 6/10 — score: 0.9359
  Restart 7/10 — score: 0.9368
  Restart 8/10 — score: 0.9367
  Restart 9/10 — score: 0.9367
  Restart 10/10 — score: 0.9369
  Best score: 0.9371

[0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 11,
 11,
 8,
 12,
 0,
 0,
 10,
 10,
 0,
 12,
 10,
 0,
 3,
 0,
 3,
 0,
 5,
 1,
 3,
 0,
 8,
 11,
 0,
 0,
 8,
 8,
 0,
 1,
 1,
 5,
 0,
 1,
 5,
 7,
 2,
 1,
 1,
 1,
 10,
 1,
 1,
 1,
 1,
 10,
 0,
 10,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 9,
 5,
 5,
 5,
 0,
 5,
 5,
 0,
 1,
 1,
 3,
 5,
 5,
 5,
 8,
 1,
 1,
 5,
 5,
 5,
 0,
 0,
 0,
 0,
 10,
 7,
 7,
 0,
 0,
 5,
 5,
 1,
 7,
 6,
 7,
 6,
 6,
 5,
 2,
 10,
 5,
 5,
 5,
 5,
 0,
 0,
 0,
 5,
 5,
 5,
 5,
 3,
 5,
 1,
 8,
 4,
 5,
 0,
 0,
 0,
 5,
 5,
 0,
 5,
 5,
 10,
 7,
 4,
 4,
 11,
 5,
 9,
 2,
 5,
 5,
 10,
 0,
 4,
 0,
 3,
 3,
 0,
 3,
 10,
 3,
 5,
 2,
 5,
 3,
 0,
 0,
 8,
 5,
 0,
 12,
 12,
 12,
 12,
 12,
 12,
 0,
 5,
 5,
 0,
 3,
 5,
 11,
 12,
 11,
 0,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 9,
 3,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 12,
 12,
 2,
 2,
 0,
 5,
 0,
 0,
 5,
 0,
 5,
 1,
 9,
 5,
 0,
 5,
 0,
 12,
 1,
 1,
 5,
 7,
 5,
 0,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 0,
 5,
 3,
 1,
 5,
 11,
 4,
 4,
 0,
 10,
 0,
 5,
 11,
 5,
 5,
 5,
 7,
 1,
 1,
 7,
 6,
 0,
 5,
 5,
 5,
 5,
 1,
 1,
 1,
 0,
 1,
 2,
 5,
 5,
 7,
 5,
 0,
 5,
 3,
 3,
 0,
 3,
 0,
 5,
 0,
 0,
 3,
 5,
 2,
 3,
 2,
 5,
 0,
 3,
 3,
 0,
 1,
 9,
 5,
 0,
 2,
 1,
 1,
 2,
 5,
 1,
 0,
 0,
 5,
 3,
 0,
 13,
 1,
 3,
 5,
 3,
 2,
 1,
 5,
 5,
 3,
 6,
 1,
 0,
 1,
 3,
 3,
 5,
 3,
 3,
 2,
 1,
 1,
 13,
 1,
 4,
 5,
 6,
 10,
 3,
 2,
 3,
 5,
 1,
 1,
 2,
 1,
 2,
 5,
 10,
 10,
 2,
 5,
 5,
 0,
 11,
 0,
 0,
 1,
 0,
 3,
 6,
 10,
 0,
 2,
 6,
 6,
 5,
 10,
 10,
 2,
 1,
 10,
 0,
 0,
 0,
 0,
 1,
 10,
 10,
 10,
 10,
 1,
 1,
 1,
 10,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 8,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 5,
 1,
 1,
 0]

In [ ]:
soft

[[0, 12],
 [0, 1, 5],
 [0],
 [2],
 [2],
 [0],
 [0, 1],
 [0, 11, 12],
 [0, 5],
 [0, 5, 11],
 [8, 11, 12],
 [0, 11],
 [0, 5, 8],
 [0, 12],
 [0, 12],
 [0],
 [7, 9, 10],
 [10],
 [0, 1, 5],
 [0, 8, 12],
 [10],
 [0],
 [3],
 [0, 1, 8],
 [0, 3],
 [0],
 [0, 5, 7],
 [1, 5],
 [3],
 [0, 1, 5],
 [8],
 [1, 4, 11],
 [0],
 [0],
 [8],
 [8],
 [0],
 [1],
 [1],
 [5, 7],
 [0],
 [0, 1, 5],
 [0, 5, 7],
 [0, 7, 12],
 [2, 10],
 [1, 5],
 [1],
 [1],
 [3, 7, 10],
 [1, 5, 7],
 [1],
 [1],
 [1],
 [5, 7, 10],
 [0, 3, 5],
 [10],
 [7],
 [7],
 [7],
 [7],
 [7],
 [7],
 [7],
 [5],
 [9],
 [0, 3, 5],
 [5],
 [0, 5, 7],
 [0, 3],
 [1, 4, 5],
 [0, 3, 5],
 [0, 1, 3],
 [0, 1, 5],
 [0, 1, 5],
 [1, 3, 5],
 [0, 3, 5],
 [5, 6],
 [5],
 [0, 8],
 [1, 3, 8],
 [1, 5],
 [1, 3, 5],
 [5],
 [5],
 [0, 5],
 [0, 5, 10],
 [0, 1],
 [0, 1, 8],
 [10],
 [7],
 [7],
 [0, 8, 12],
 [0],
 [3, 5],
 [3, 5, 8],
 [1, 5, 8],
 [7],
 [6],
 [7],
 [6],
 [6, 7, 10],
 [0, 5, 7],
 [2],
 [5, 7, 10],
 [5],
 [0, 3, 5],
 [3, 5],
 [3, 5],
 [0, 3, 5],
 [0, 3, 5],
 [0],
 [0, 3, 5],
 [5],
 [5],
 [0, 5],
 [0, 3],
 [5],
 [1, 4, 5],
 [8],
 [4],
 [3, 4, 5],
 [0],
 [0, 8],
 [0, 1, 4],
 [0, 5, 12],
 [0, 3, 5],
 [0, 5, 9],
 [0, 5, 9],
 [5, 10],
 [10],
 [7],
 [4],
 [4],
 [4, 11, 12],
 [5, 7],
 [9],
 [2],
 [0, 3, 5],
 [0, 5, 7],
 [10],
 [0],
 [4],
 [0, 3],
 [0, 3],
 [0, 3],
 [0],
 [0, 3, 5],
 [10],
 [3, 5],
 [0, 5],
 [2],
 [5],
 [1, 3, 5],
 [0, 1, 3],
 [0],
 [8],
 [0, 3, 5],
 [0, 3, 5],
 [12],
 [12],
 [12],
 [12],
 [12],
 [0, 12],
 [0, 1, 3],
 [5, 6, 7],
 [3, 5],
 [0, 8, 12],
 [0, 1, 3],
 [5, 11],
 [11],
 [12],
 [0, 5, 11],
 [0, 5],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [9],
 [0, 3],
 [0, 1, 5],
 [0, 1, 5],
 [0, 4, 5],
 [0],
 [0],
 [0],
 [0],
 [0, 1],
 [12],
 [0, 4, 12],
 [2],
 [2],
 [0, 1, 3],
 [5],
 [0],
 [0, 3, 5],
 [5],
 [0, 1],
 [3, 4, 5],
 [0, 1, 3],
 [9],
 [5],
 [0, 5],
 [0, 5, 8],
 [0, 5],
 [12],
 [1],
 [1],
 [5],
 [7],
 [0, 4, 5],
 [0, 5, 11],
 [0, 3, 5],
 [0, 5],
 [0, 1, 5],
 [0, 3, 5],
 [0, 5],
 [5],
 [5],
 [0],
 [5],
 [0, 3, 5],
 [0, 1],
 [5],
 [4, 5, 11],
 [4],
 [4],
 [0],
 [0, 6, 10],
 [0, 7],
 [3, 5],
 [0, 11, 12],
 [5],
 [0, 4, 5],
 [5, 7, 10],
 [7],
 [0, 1, 5],
 [1],
 [5, 7, 9],
 [6],
 [0, 1],
 [5],
 [5],
 [5],
 [5],
 [1],
 [1, 3],
 [1, 3, 5],
 [0, 1, 3],
 [0, 1],
 [2],
 [5],
 [1, 3, 5],
 [5, 7],
 [1, 5, 7],
 [0],
 [1, 3, 5],
 [3, 5, 6],
 [0, 3],
 [0, 3, 5],
 [0, 3, 5],
 [0, 3, 5],
 [5],
 [0, 5],
 [0, 3, 5],
 [3],
 [1, 5, 7],
 [2],
 [3],
 [2],
 [5],
 [0],
 [3, 10, 11],
 [0, 3, 5],
 [0, 1],
 [1],
 [9],
 [0, 3, 5],
 [0, 5],
 [2],
 [1, 3],
 [1, 3],
 [2],
 [5],
 [1, 5],
 [0],
 [0, 1, 3],
 [3, 5],
 [3],
 [0, 3, 5],
 [2, 13],
 [0, 1, 5],
 [0, 3],
 [0, 3, 5],
 [0, 3, 5],
 [2],
 [1],
 [0, 1, 5],
 [5],
 [0, 1, 3],
 [6],
 [1],
 [0, 1, 3],
 [0, 1, 5],
 [0, 3, 5],
 [0, 1, 3],
 [5],
 [1, 3],
 [3],
 [2],
 [0, 1, 5],
 [1, 10, 11],
 [13],
 [1, 3],
 [4],
 [5],
 [6],
 [10],
 [3],
 [2],
 [3, 5],
 [0, 5],
 [1, 3],
 [1, 3],
 [2],
 [1],
 [2],
 [5, 6, 8],
 [10],
 [10],
 [2],
 [3, 5],
 [5],
 [0, 3, 5],
 [8, 10, 11],
 [0, 1, 3],
 [0, 5],
 [1, 5, 7],
 [0, 1, 5],
 [3, 5, 6],
 [6],
 [10],
 [0, 5, 8],
 [2],
 [6],
 [6],
 [0, 5],
 [10],
 [7, 10],
 [2],
 [0, 1, 8],
 [10],
 [0],
 [0, 1],
 [0],
 [0, 5, 10],
 [1, 5],
 [10],
 [10],
 [10],
 [10],
 [1, 3, 5],
 [1],
 [1],
 [10],
 [1],
 [0],
 [1],
 [0, 1, 3],
 [0, 1, 3],
 [0, 1, 3],
 [0, 1],
 [1],
 [1],
 [1, 3],
 [0, 1],
 [1],
 [1],
 [1],
 [0, 1],
 [8],
 [1, 3],
 [1],
 [1, 8],
 [1],
 [0, 1, 5],
 [1],
 [2],
 [1, 3],
 [1],
 [1],
 [1],
 [1],
 [1],
 [2],
 [0, 1, 5],
 [2],
 [1],
 [2],
 [1],
 [2],
 [1, 5],
 [0, 1],
 [0, 1],
 [0]]

In [ ]:
df = df.with_columns(pl.Series("cluster", clusters))

with pl.Config(set_tbl_rows=20):
    display(df["cluster"].value_counts())

shape: (14, 2)
┌─────────┬───────┐
│ cluster ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 9       ┆ 5     │
│ 5       ┆ 86    │
│ 4       ┆ 7     │
│ 8       ┆ 8     │
│ 11      ┆ 21    │
│ 12      ┆ 12    │
│ 3       ┆ 32    │
│ 10      ┆ 24    │
│ 2       ┆ 26    │
│ 13      ┆ 2     │
│ 6       ┆ 9     │
│ 1       ┆ 77    │
│ 0       ┆ 87    │
│ 7       ┆ 17    │
└─────────┴───────┘

In [ ]:
counts = df["cluster"].value_counts()
thresh = counts.filter(pl.col("count") ** (1 / 3) > 3)

In [7]:
thresh

shape: (4, 2)
┌─────────┬───────┐
│ cluster ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 0       ┆ 87    │
│ 5       ┆ 86    │
│ 1       ┆ 77    │
│ 3       ┆ 32    │
└─────────┴───────┘

In [8]:
for i in range(10):
    print(f"{i}: {i**3}")

0: 0
1: 1
2: 8
3: 27
4: 64
5: 125
6: 216
7: 343
8: 512
9: 729

In [ ]:
embed_list = df["embedding"].to_list()
clusters, soft, samples, iters = create_cluster(embed_list, run_num=1)

df = df.with_columns(pl.Series("cluster2", clusters))
with pl.Config(set_tbl_rows=20):
    display(df.select(["cluster", "cluster2"]))