In [3]:
from clustering.clustering import create_cluster
import polars as pl
from genai.mistral import get_mistral_cluster_tags, ClusterWithTags
import time

folder = "ribier_v1"
df = pl.read_parquet(f"./books_work/{folder}/data/{folder}.parquet")
docs = df["embedding"].to_list()
print("Creating clusters...")
cluster, soft, samples, iters = create_cluster(docs, run_num=1)
df = df.with_columns(
    pl.Series("cluster", cluster),
    pl.Series("soft_cluster", soft),
)
print("Calculating cluster counts and percentages...")
n = len(df)
cluster_counts = df["cluster"].value_counts().sort("cluster")
cluster_counts = cluster_counts.with_columns(cluster_perc=cluster_counts["count"] / n)
clusters_to_sub_df = cluster_counts.filter(pl.col("count") ** (1 / 3) >= 3)
clusters_to_sub = clusters_to_sub_df["cluster"].to_list()
df = df.with_columns(sub_cluster=pl.lit(-1).cast(pl.Int64))
df = df.with_columns(sub_labels=pl.lit(None).cast(pl.List(pl.Utf8)))

print(f"Clusters to sub-cluster: {clusters_to_sub}")
# Let's get sub-clusters for clusters that have enough samples, and get their tags using Mistral
for c in clusters_to_sub:
    cluster_count = clusters_to_sub_df.filter(pl.col("cluster") == c)["count"][0] ** (
        1 / 3
    )
    cluster_count = int(cluster_count)
    sub_df = df.filter(pl.col("cluster") == c)
    sub_docs = sub_df["embedding"].to_list()
    sub_cluster, _, sub_samples, _ = create_cluster(
        sub_docs, run_num=1, soft_assign=False, num_clusters=cluster_count
    )
    # Get sub-cluster tags using Mistral
    print(f"Getting tags for sub-cluster {c}...")
    sample_docs: list[ClusterWithTags] = [
        ClusterWithTags(label=i, tags=df[s].select("markdown").to_series().to_list())
        for i, s in enumerate(sub_samples)
    ]
    res = get_mistral_cluster_tags(sample_docs)
    sub_samples_dict = {item.label: item.tags for item in res}
    sub_samples_list = [sub_samples_dict.get(c) for c in sub_cluster]

    # Assign sub_cluster to sub_df
    sub_df = sub_df.with_columns(pl.Series("sub_c", sub_cluster))
    sub_df = sub_df.with_columns(pl.Series("sub_s", sub_samples_list))

    df = df.join(
        sub_df.select(["chunk_id", "sub_c", "sub_s"]), on="chunk_id", how="left"
    )
    df = df.with_columns(
        sub_cluster=(
            pl.when(pl.col("sub_c").is_not_null())
            .then(pl.col("sub_c"))
            .otherwise(pl.col("sub_cluster"))
        ),
        sub_labels=(
            pl.when(pl.col("sub_s").is_not_null())
            .then(pl.col("sub_s"))
            .otherwise(pl.col("sub_labels"))
        ),
    )
    df = df.drop("sub_c")
    df = df.drop("sub_s")
    # If you want to fill nulls with a default value (e.g., -1), uncomment:
    df = df.with_columns(pl.col("sub_cluster").fill_null(-1))

# Now let's get the cluster tags for the main clusters using Mistral
sample_docs: list[ClusterWithTags] = [
    ClusterWithTags(label=i, tags=df[s].select("markdown").to_series().to_list())
    for i, s in enumerate(samples)
]

res = get_mistral_cluster_tags(sample_docs)
res_dict = {item.label: item.tags for item in res}
res_list = [res_dict.get(c) for c in cluster]
df = df.with_columns(pl.Series("cluster_tags", res_list))
df

Creating clusters...
  Estimated number of clusters: 14
  Restart 1/10 (seed 10) — score: 0.9375
  Restart 2/10 (seed 11) — score: 0.9371
  Restart 3/10 (seed 12) — score: 0.9384
  Restart 4/10 (seed 13) — score: 0.9376
  Restart 5/10 (seed 14) — score: 0.9375
  Restart 6/10 (seed 15) — score: 0.9376
  Restart 7/10 (seed 16) — score: 0.9374
  Restart 8/10 (seed 17) — score: 0.9372
  Restart 9/10 (seed 18) — score: 0.9374
  Restart 10/10 (seed 19) — score: 0.9379
  Best score: 0.9384
Calculating cluster counts and percentages...
Clusters to sub-cluster: [0, 2, 12]
  Restart 1/10 (seed 10) — score: 0.9430
  Restart 2/10 (seed 11) — score: 0.9433
  Restart 3/10 (seed 12) — score: 0.9436
  Restart 4/10 (seed 13) — score: 0.9439
  Restart 5/10 (seed 14) — score: 0.9434
  Restart 6/10 (seed 15) — score: 0.9437
  Restart 7/10 (seed 16) — score: 0.9447
  Restart 8/10 (seed 17) — score: 0.9430
  Restart 9/10 (seed 18) — score: 0.9442
  Restart 10/10 (seed 19) — score: 0.9431
  Best score: 0.9447
Getting tags for sub-cluster 0...
Using Mistral model: mistral-small-latest. Instituting a delay of 60 seconds between API calls to avoid rate limits.
  Restart 1/10 (seed 10) — score: 0.9476
  Restart 2/10 (seed 11) — score: 0.9473
  Restart 3/10 (seed 12) — score: 0.9468
  Restart 4/10 (seed 13) — score: 0.9469
  Restart 5/10 (seed 14) — score: 0.9471
  Restart 6/10 (seed 15) — score: 0.9476
  Restart 7/10 (seed 16) — score: 0.9467
  Restart 8/10 (seed 17) — score: 0.9469
  Restart 9/10 (seed 18) — score: 0.9465
  Restart 10/10 (seed 19) — score: 0.9473
  Best score: 0.9476
Getting tags for sub-cluster 2...
Using Mistral model: mistral-small-latest. Instituting a delay of 60 seconds between API calls to avoid rate limits.
  Restart 1/10 (seed 10) — score: 0.9470
  Restart 2/10 (seed 11) — score: 0.9457
  Restart 3/10 (seed 12) — score: 0.9459
  Restart 4/10 (seed 13) — score: 0.9467
  Restart 5/10 (seed 14) — score: 0.9462
  Restart 6/10 (seed 15) — score: 0.9464
  Restart 7/10 (seed 16) — score: 0.9463
  Restart 8/10 (seed 17) — score: 0.9464
  Restart 9/10 (seed 18) — score: 0.9463
  Restart 10/10 (seed 19) — score: 0.9469
  Best score: 0.9470
Getting tags for sub-cluster 12...
Using Mistral model: mistral-small-latest. Instituting a delay of 60 seconds between API calls to avoid rate limits.
Using Mistral model: mistral-small-latest. Instituting a delay of 60 seconds between API calls to avoid rate limits.

shape: (338, 14)
┌───────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ letter_id ┆ id   ┆ markdown   ┆ pdf_pages  ┆ … ┆ soft_clust ┆ sub_cluste ┆ sub_label ┆ cluster_t │
│ ---       ┆ ---  ┆ ---        ┆ ---        ┆   ┆ er         ┆ r          ┆ s         ┆ ags       │
│ u32       ┆ u32  ┆ str        ┆ list[i64]  ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆      ┆            ┆            ┆   ┆ list[i64]  ┆ i64        ┆ list[str] ┆ list[str] │
╞═══════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 10000     ┆ 1000 ┆ LE PAPE    ┆ [46]       ┆ … ┆ [10]       ┆ -1         ┆ null      ┆ ["PapalCo │
│           ┆      ┆ PAVL III.  ┆            ┆   ┆            ┆            ┆           ┆ nciliarDi │
│           ┆      ┆ AV ROT     ┆            ┆   ┆            ┆            ┆           ┆ plomacy", │
│           ┆      ┆ FRANC…     ┆            ┆   ┆            ┆            ┆           ┆ "R…       │
│ 10001     ┆ 1001 ┆ LETTRE DE  ┆ [46, 47]   ┆ … ┆ [2, 9, 12] ┆ 3          ┆ ["PapalMe ┆ ["PapalDi │
│           ┆      ┆ MONLVC AV  ┆            ┆   ┆            ┆            ┆ diationAt ┆ plomacy", │
│           ┆      ┆ CARDINAL   ┆            ┆   ┆            ┆            ┆ tempts",  ┆ "Neutrali │
│           ┆      ┆ D…         ┆            ┆   ┆            ┆            ┆ "Su…      ┆ ty…       │
│ 10002     ┆ 1002 ┆ LETTRE DES ┆ [47, 48]   ┆ … ┆ [2, 9, 12] ┆ 0          ┆ ["Diploma ┆ ["Diploma │
│           ┆      ┆ AVOTERS ET ┆            ┆   ┆            ┆            ┆ ticNegoti ┆ ticEspion │
│           ┆      ┆ CONSEILL…  ┆            ┆   ┆            ┆            ┆ ations",  ┆ age",     │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ "Su…      ┆ "Renai…   │
│ 10003     ┆ 1003 ┆ REMARQUES  ┆ [48, 49, … ┆ … ┆ [8]        ┆ -1         ┆ null      ┆ ["Diploma │
│           ┆      ┆ SVR LADITE ┆ 54]        ┆   ┆            ┆            ┆           ┆ ticNegoti │
│           ┆      ┆ VILLE DE … ┆            ┆   ┆            ┆            ┆           ┆ ations",  │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆           ┆ "Co…      │
│ 10003     ┆ 1003 ┆ Cethol.    ┆ [48, 49, … ┆ … ┆ [10, 13]   ┆ -1         ┆ null      ┆ ["PapalCo │
│           ┆      ┆ 1192. 6    ┆ 54]        ┆   ┆            ┆            ┆           ┆ nciliarDi │
│           ┆      ┆ commiæer   ┆            ┆   ┆            ┆            ┆           ┆ plomacy", │
│           ┆      ┆ Janoe…     ┆            ┆   ┆            ┆            ┆           ┆ "R…       │
│ …         ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 10261     ┆ 1261 ┆ DE L'AUBES ┆ [656, 657] ┆ … ┆ [1]        ┆ -1         ┆ null      ┆ ["GermanP │
│           ┆      ┆ PINE.      ┆            ┆   ┆            ┆            ┆           ┆ rincesRes │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆           ┆ istance", │
│           ┆      ┆ --- ## LE  ┆            ┆   ┆            ┆            ┆           ┆ "E…       │
│           ┆      ┆ ROY…       ┆            ┆   ┆            ┆            ┆           ┆           │
│ 10262     ┆ 1262 ┆ # A        ┆ [657, 658] ┆ … ┆ [0, 2, 3]  ┆ 3          ┆ ["PapalMe ┆ ["PapalDi │
│           ┆      ┆ MONSIEUR   ┆            ┆   ┆            ┆            ┆ diationAt ┆ plomacy", │
│           ┆      ┆ LE DAVHIN. ┆            ┆   ┆            ┆            ┆ tempts",  ┆ "Neutrali │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ "Su…      ┆ ty…       │
│           ┆      ┆ Le Ca…     ┆            ┆   ┆            ┆            ┆           ┆           │
│ 10263     ┆ 1263 ┆ LE         ┆ [658, 659] ┆ … ┆ [0]        ┆ 0          ┆ ["PapalDi ┆ ["Diploma │
│           ┆      ┆ CARDINAL   ┆            ┆   ┆            ┆            ┆ plomacy", ┆ ticAllian │
│           ┆      ┆ DE BOLOGNE ┆            ┆   ┆            ┆            ┆ "FrancoIm ┆ ces",     │
│           ┆      ┆ ## AV R…   ┆            ┆   ┆            ┆            ┆ pe…       ┆ "AntiH…   │
│ 10264     ┆ 1264 ┆ AV ROT.    ┆ [659, 660] ┆ … ┆ [0]        ┆ 0          ┆ ["PapalDi ┆ ["Diploma │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ plomacy", ┆ ticAllian │
│           ┆      ┆ Du Mortier ┆            ┆   ┆            ┆            ┆ "FrancoIm ┆ ces",     │
│           ┆      ┆ Ambaffadeu ┆            ┆   ┆            ┆            ┆ pe…       ┆ "AntiH…   │
│           ┆      ┆ …          ┆            ┆   ┆            ┆            ┆           ┆           │
│ 10265     ┆ 1265 ┆ ## A       ┆ [660, 661] ┆ … ┆ [0, 2, 12] ┆ 3          ┆ ["PapalMe ┆ ["PapalDi │
│           ┆      ┆ MONSIEUR   ┆            ┆   ┆            ┆            ┆ diationAt ┆ plomacy", │
│           ┆      ┆ L'ADMIRAL  ┆            ┆   ┆            ┆            ┆ tempts",  ┆ "Neutrali │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ "Su…      ┆ ty…       │
│           ┆      ┆ Que c…     ┆            ┆   ┆            ┆            ┆           ┆           │
└───────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [4]:
df.write_parquet(f"./books_work/ribier_v1/data/ribier_v1.parquet")

In [5]:
import polars as pl

df = pl.read_parquet(f"./books_work/ribier_v1/data/ribier_v1.parquet")
df.head()

shape: (5, 14)
┌───────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ letter_id ┆ id   ┆ markdown   ┆ pdf_pages  ┆ … ┆ soft_clust ┆ sub_cluste ┆ sub_label ┆ cluster_t │
│ ---       ┆ ---  ┆ ---        ┆ ---        ┆   ┆ er         ┆ r          ┆ s         ┆ ags       │
│ u32       ┆ u32  ┆ str        ┆ list[i64]  ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆      ┆            ┆            ┆   ┆ list[i64]  ┆ i64        ┆ list[str] ┆ list[str] │
╞═══════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 10000     ┆ 1000 ┆ LE PAPE    ┆ [46]       ┆ … ┆ [10]       ┆ -1         ┆ null      ┆ ["PapalCo │
│           ┆      ┆ PAVL III.  ┆            ┆   ┆            ┆            ┆           ┆ nciliarDi │
│           ┆      ┆ AV ROT     ┆            ┆   ┆            ┆            ┆           ┆ plomacy", │
│           ┆      ┆ FRANC…     ┆            ┆   ┆            ┆            ┆           ┆ "R…       │
│ 10001     ┆ 1001 ┆ LETTRE DE  ┆ [46, 47]   ┆ … ┆ [2, 9, 12] ┆ 3          ┆ ["PapalMe ┆ ["PapalDi │
│           ┆      ┆ MONLVC AV  ┆            ┆   ┆            ┆            ┆ diationAt ┆ plomacy", │
│           ┆      ┆ CARDINAL   ┆            ┆   ┆            ┆            ┆ tempts",  ┆ "Neutrali │
│           ┆      ┆ D…         ┆            ┆   ┆            ┆            ┆ "Su…      ┆ ty…       │
│ 10002     ┆ 1002 ┆ LETTRE DES ┆ [47, 48]   ┆ … ┆ [2, 9, 12] ┆ 0          ┆ ["Diploma ┆ ["Diploma │
│           ┆      ┆ AVOTERS ET ┆            ┆   ┆            ┆            ┆ ticNegoti ┆ ticEspion │
│           ┆      ┆ CONSEILL…  ┆            ┆   ┆            ┆            ┆ ations",  ┆ age",     │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ "Su…      ┆ "Renai…   │
│ 10003     ┆ 1003 ┆ REMARQUES  ┆ [48, 49, … ┆ … ┆ [8]        ┆ -1         ┆ null      ┆ ["Diploma │
│           ┆      ┆ SVR LADITE ┆ 54]        ┆   ┆            ┆            ┆           ┆ ticNegoti │
│           ┆      ┆ VILLE DE … ┆            ┆   ┆            ┆            ┆           ┆ ations",  │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆           ┆ "Co…      │
│ 10003     ┆ 1003 ┆ Cethol.    ┆ [48, 49, … ┆ … ┆ [10, 13]   ┆ -1         ┆ null      ┆ ["PapalCo │
│           ┆      ┆ 1192. 6    ┆ 54]        ┆   ┆            ┆            ┆           ┆ nciliarDi │
│           ┆      ┆ commiæer   ┆            ┆   ┆            ┆            ┆           ┆ plomacy", │
│           ┆      ┆ Janoe…     ┆            ┆   ┆            ┆            ┆           ┆ "R…       │
└───────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [6]:
with pl.Config(tbl_rows=26):
    display(df["cluster"].value_counts().sort("cluster"))

shape: (14, 2)
┌─────────┬───────┐
│ cluster ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 0       ┆ 40    │
│ 1       ┆ 17    │
│ 2       ┆ 97    │
│ 3       ┆ 21    │
│ 4       ┆ 14    │
│ 5       ┆ 18    │
│ 6       ┆ 4     │
│ 7       ┆ 14    │
│ 8       ┆ 7     │
│ 9       ┆ 7     │
│ 10      ┆ 5     │
│ 11      ┆ 9     │
│ 12      ┆ 61    │
│ 13      ┆ 24    │
└─────────┴───────┘

In [5]:
cluster13_samples = (
    df.filter(pl.col("cluster1") == 13)
    .select("markdown")
    .sample(5)
    .to_series()
    .to_list()
)
cluster13_samples

["\n\nJe renferme dans ce Livre le refe du Regne de François I. c'est à dire depuis 1541. jusqu'en 1547. au mois de Mars ; n'ayant pas affex de pieces pour faire vn Livre de chaque année, comme nous avons commencé. La disgrace de Mr. le Connesable en est la cause: car comme les Negotiations des Ambassadors et autres Affaires ne luy furent plus addresfées et ont passé en d'autres mains, se n'en ay pû recouurer les Puses Originales dans les Maisons anciennes où j'ay trouvé les Precedentes sous François I. et les faisantes sous Henry II. J's semble que le Roy pendant la disgrace Mr. le Connesable, pris luy-même le jour des Affaires. Neantmoins Mr. l'Admiral fut comme le Fanory, et après luy ceux qui eurent le plus de credit, même dans les affaires d'Etat, furent les Srs. Bayard et Bochete tous deux Secretaires des Finances. Aussi furent-ils éloignés de la Cour, et même ledit Bayard rudement traité sous Henry II. lors que le Connesable fut ressabby en faveur.\n\nLes Secretaires d'Etat en ce répa-la s'appellissent encore Secretaires des Finances.\n\n",
 "Piece precedente.\n\nL'A première observation regarde le dater de ce célèbre liêt de Justice, qui est du 13. Janvier 1336. Et toutefois à commencer l'année, comme je fais en tout ce recueil, par le premier de Janvier selon notre vague présent, cette royale action est indubitablement de Janvier 1337. Mais lors l'année en France commençant &amp; sinissant par sa révolution circulaire à Pasques, les mois par conséquent de Janvier, Feurier est bien encore entièrement de 1336. Et peut-être aussi tout le mois de Mars &amp; une partie d'Auril, parce que la Feste de Pasques qui est mobile avance ou retarde tous les ans.\n\nCette différence qu'il y a un entre nous &amp; nos voisins pour l'ordre des mois &amp; le dater des années a introduit beaucoup d'embaraux &amp; d'erreurs en notre histoire &amp; de contrarictez parmi nos historiens, les uns comptant &amp; marquants les années à la mode de France, les autres les commençant au mois de Janvier &amp; les sinisants en Decembre, tellement que beaucoup de choses de conséquence publiques &amp; particulières se trouvent cottées directement &amp; d'une année plûtos ou plus tard par l'un que par l'autre, ce qui embarasse les lecteurs, &amp; qui de plus est causé que non seulement pour les mois de Janvier, Feurier, Mars &amp; Auril : mais encore à l'égard des autres mois, quelques historiens ont mis beaucoup de choses hors de leur vray &amp; naturel rang, faisant marcher les dernières venues devant celles qui les ont précédées : Si je voulois produire un recueil de telles fautes &amp; mécontes il y en auroit un juste volume : certes nos historiens nous eussent fait soulagement si par leurs Préfaces ou dès le commencement de leurs Litures, ils nous eussent adurtii de la forme d'année qu'ils souiroient en leurs dates.\n\nMais ce qui est encore de plus absurde, quelqu'un d'eux ont confirmé leurs dates tantôt au solle d'Italie, tantôt à celui de France sans aucun discernement, comme si cela leur est bien indiferent : Et toutefois il est nécessaire aux historiens d'être exacts &amp; ponctuels au temps, à peine de grandes confusions, désordres &amp; sausserez en leurs relations.\n\nIl faut certainement avoir bien étudié les histoires, tant générales que particulières, pour démoser en ce qui est du temps leurs contradictions, et savoir mettre chaque chose en son ordre, autrement on s'enveloppe facilement s'y mettre dans leurs erreurs &amp; mécontes : je proposerai sur cela l'exemple de la pièce même dont il s'agit présentement, tous nos registres publics la datent de Janvier 1636. Or les mêmes registres &amp; tous nos historiens soit François\n\n1LIVRE I. ANNEE M. D. XXXVII. 17\n\nou estranges sont soy que Charles quint n'entra à mainarme en Provence, qu'au mois de Juillet de la meime année 1336. Amoint donc que d'avoir connoissance que les mois de Janvier, Fevrier et Mars, qui estoient ailleurs les premiers de l'année, envoient le dernier rang en France; on croiroit sans doute que le Roy François premier tint son lieu de Justice contre Charles - quint six mois auparavant la guerre de Provence, et toutefois le contraire se verifie par les Historiens, et par un grand nombre d'infinis actes publics, de même par le plaidoyé cy- devant inféré de l'Advocat General Coppel où il employe particulièrement l'entreprise de Provence comme un des principaux Chefs de la rebellion et solounie du vassal contre son Seigneur.\n\nCes diners comptes et dattes d'années que soy rencontrez dans les Lettres et Memoires d'Estat contenus en ce recueil m'ont donné jouient de la peine, par ce que soy voulu diuifer mes Lettres de Memoires par l'ordre des années et des mois, de meime des iours sans qu'il m'a esté possible, en quoy, et me suis trouvé quelques fois fort empêché, à l'égard principalement des Lettres et Memoires dattez des derniers iours de Mars des premiers d'Auril sans qu'il y ait, ny devant ny apres Pasques, Pour leur mes doutes et difficultez par demonstrations claires et mathematiques, il eust jallu consulter les vieux Calendriers, Almanachs ou Breuiaires, et chercher à quel mois et à quel tour d'iceluy etsoit lors la fette de Pasques.\n\nMais les connoissances particulières que l'avoir des choïcs qui ont précédé ou suivy ces Lettres et Memoires, du temps de quels c'estois incertain, et les autres Lettres que l'ay des mesmes deux années, entre le queller le tinoit mon esprit en suspens, m'ont esclairé et donné lumière de leur veritable temps de ordre: si toutefois ie me suis trompé en quelques uns, l'espere que toutes les personnes raisonnables, et de Lettres m'en excuseront bien franchement.\n\nJ'ob'erue donc en mon recueil notltre usage proscrite de compter, à commander l'Année par le premier iour de Janvier suivant le reglement du Roy Charles IX. article 39. de son Edict fait à Roussillon en 1363. et qu'il consirma par autre Ordonnance de 1366. reformation fort commode parce que l'année n'est plus changeante et variable comme elle etloit, les deux Polet à l'entour desquels elle fait son tour et mouvement entier (fentent le premier iour de Janvier et le dernier iour de Decembre) sont fixes, stables et permanents au lieu que la Fette de Pasques et le samey Saint s'auanoient ou retrogradoient par chacun An : ie n'ay pas voulu toutefois corriger en aucune Lettre le datte de l'Année, ie me suis contenté de mettre en marge comme on l'aurait dattee en Italie, ou comme on la dateroit presentement en France suivant notltre usage commun et l'Ordonnance de Charles IX.\n\nJ'espere que cette premiere Remarque ne déplaira pas à plusieurs personnes une fois pour toutes.\n\nLa seconde Remarque sur ce Lieu de Justice de François I. consiste en la France du Dauphin au dessous des Roys d'Escosse et de Navarre, c'estloit le Fils Aisné du Roy, et par conséquent son presomptif et legitime Successeur à la Couronne de France, comme aussi en effet il regna depuis sous le Nem. d'Henry II.\n\nIl avoit pris le tiltre de Dauphin l'année precedente incontinent apres la2\n\n\n\n# LETTRES ET MEMOIRES DESTAT,\n\nmort du Dauphin François, son aigné, non pas en qualité de son berstier, mais comme ettans lors le Fils aigné du Roy regnant, parce que suivant la convention faite entre Philippes de Valois &amp; Humbert Dauphin de Vienne, le titre de Dauphin apartient toujours aux Fils aignés du Roy regnant &amp; subordonnants de sorte que l'Aigné de naissance décédant, le second entre en sa place, comme ettans désormais l'Aigné, &amp; dès lors il prend en son Etufton les plaines Armes de France &amp; de Dauphiné, Ainsf le troizième en cas de mort dude second Fils, mais si le Roy regnant n'a point d'Enfans mâles, son Frere ou autre Collateral que la Couronne regarde, ne prend point le titre de Dauphin, il est voy cependant à la Royauté.\n\nOr pour venir à la préférence, celle du Roy de Navarre sur ledit Dauphin m'est suspecté, &amp; je croy qu'il y a erreur en ma Copie, parce que j'ay veu en Extrait des Registres du Parlement où le Dauphin est mis le premier, comme aussi je le trouve en cette même situation en deux diures Chapitres de du Tillet, où il est fait mention de ce Lait de l'utice du grand Roy François.\n\nLa Réflexion donc que je sais sur sa Scance se réduit au Roy d'Escalf seul, lequel sans doute fut assis au dessus de luy, &amp; n'y forma le Dauphin aucune difficulté ou protettation, &amp; toutefois j'ay après de diures Historiens, &amp; particulièrement du même du Tillet très-exact &amp; fidel raporteur des rangs &amp; préeminences des Princes du rang Royal &amp; des autres grands de ce Royaume, &amp; qui les a extraits avec grand soin des titres originaux, qu'anciennement les fils aignés des Roys de France, (ils s'intituloient ainsi &amp; non pas fils de France par abrégé) préféroient ce titre à celui de Roy de quelques Provinces de dehors, de sorte que dans leurs Lettres Patentes, Contracts &amp; Actes publics, l'honneur &amp; la dignité de leur naissance précédait leurs Royautés estrangeres : les exemples en sont de Philippes le Bel &amp; Louis Hutin, lesquels avant que d'être Roys de France le furent du Royaume de Navarre, comme Heritiers de leur dessuncle Miro, &amp; toutefois ils s'intituloient toujours fils aignés du Roy de France, Roys de Navarre, &amp; ensuite Ducs, &amp;c.\n\nLes Cadets ou Puissés n'en voient pas ainsi, ils mettaient leurs Royautés quand ils en avaient les premières en leur titres, &amp; ensuite celle des fils de Frise, au dessus même des Duchés &amp; Comtés qu'ils tenaient en souveraineté, cela fut encore observé au dernier fécile par le Duc d'Anjou frère du Roy Henry troisième, car il s'intituloit fils de France Duc de Lothiers, Brabant, Gveldes, Anjou, &amp;c.\n\nCe n'est donc pas le titre de Dauphin qui donne la préférence &amp; autres droits &amp; préeminences à ceux qui le portent, il estoit avant qu'il fust voy à la Couronne inférieurs aux Ducs : Et même j'ay veu plusieurs lettres patentes du Dauphin Charles V. &amp; entre-autres celles du mois d'Août, 1338. &amp; du 29. Novembre 1339. en faveur des Célestins de Paris, par lesquelles il s'intitule fils aigné du Roy, Duc de Normandie &amp; Dauphin de Viennois, mettant ainsi la qualité de Duc devant celle de Dauphin, laquelle en effet n'est pas éminente &amp; relevée d'elle-même par dessus les Duchés : Mais c'est qu'elle désigne le Fils aigné du Roy, entre lequel aigné &amp; ses frères il y a une grande différence &amp; disparité puisque selon le cours ordinaire de Nature il doit être leur Roy, &amp; eux ses Subjets, aussi reluit-il d'ici des rayons de la Majesté Royale, &amp; bien souvent ce Soleil lusant est adoré plus que le couchant : Tellement qu'il ne faut pas trou-LIVRE I. ANNEE M. D. XXXVII. 19\n\nner étrange, ny interpréter à excès d'ambition que les fils Aînés de nos Roys\nse soient égalés aux Roys d'autres Nations &amp; qu'ils ayant mis ce glorieux\ntitre de fils Aîné du Roy de France au dessus de leurs Royautés étrangères, afin\nmême de témoigner publiquement l'affection &amp; l'effime qu'ils avaient pour la\nFrance leur naturelle patrie.\n\nMais pourtant il faut auouïr qu'aux Assemblies &amp; Ceremonies de\nFrance, la dignité Royale est en possession de précédé, celle des Fils Aînés\nde nos Roys, l'exemple n'en est pas seulement au lieu de Justice de Fran-\nçois I. dont il s'agit maintenant, cela s'ob'erra aussi depuis en la personne du\nDauphin fils d'Henry second, après qu'il eut époué Marie de Lorraine\nReyne d'Escosse, car il prit toujours la qualité de Roy d'Escosse devant celle\nde Dauphin, qui marque le fils Aîné du Roy, &amp; même ordinairement on\nl'apellot le Roy Dauphin ; J'ay une Lettre Originale que le Parlement de\nGrenoble luy écrivit qui est suscrite ; Au Roy Dauphin nostre Souverain\nSeigneur.\n\nOn pourroit dire que ce fut un vage nouvellement introduit par le Roy\nFrançois premier en faveur de son nouveau Gendre Jacques cinquième Roy\nd'Escosse, pour la satisfaction duquel il avait tant de passion qu'il obligea la\nCour de Parlement à lier rendre un devoir extraordinaire le dernier jour du\nmoit précédent quand il fit son entrée à Paris, &amp; d'aller au devant de lier en\nrobes rouges depuis le Palais jusqu'à saint Anthoine des Champs, n'onobstant\nles remonstrances qui lier furent faites que ces honneur auoit toujours esté re-\nferué aux personnes seules des Roys &amp; Roynes de France ; Il y auroit donc\nlieu de penser, que ce grand Prince extrêmement franc &amp; liberal de ses fa-\nneurs envers ceux qu'il aymoit, désira si ardamment en combler son Gendre qui\nestoit allé d'Escosse en Provence lier offrir generusement son service contre\nl'Empereur, qu'il disposa le Dauphin à lier ceder volontairement sa place &amp;\nse mettre au dessous de lier, sans tirer à conséquence, tout ainsi qu'il auoit voulu\nque la Cour allât saluer ce même Roy d'Escosse auer autant de relèpence de\nCeremonie que leurs propres Maîtres de France.",

In [7]:
cluster9_sampels = (
    df.filter(pl.col("cluster1") == 9)
    .select("markdown")
    .sample(5)
    .to_series()
    .to_list()
)
cluster9_sampels

["L'Etat d'Aurances que le Roy encoye présentement par doutes, l'Empereur, luy fera les très affectueuses &amp; très cordiales recommandations dudit Sr. Et aptes luy auoit présenté les Lettres de Créance qu'il luy écrit, luy dira qu'étant naguères retourné le Sr. César Canteline, cy-deuant dépêché pour le fait de la Treue générale entre la Chreštientė &amp; le Turc ; ledit Sr. Roy pour toujours correspondre à la bonne &amp; parfaite amitié que Dieu a mise &amp; rétablie entre l'Empereur &amp; luy, a bien voulu l'adulser &amp; faire participant de tout ce qui a été négotié envers le Turc, en ce qui concernoit le fait de ladite Treue générale. Et pour luy faire entendre clairement &amp; à la vérité comme les choses s'y font passées; c'est qu'à Partiuée dudit Canteline p. d'duets le Sr. Rincon, il luy décera entièrement la charge qu'il auoit, &amp; l'occasion pour laquelle il eftoit là envoyé : &amp; ce fait, ils se transporteront ensemble à la Porte dudit Turc, auquel Rincon suiuant l'intention du Roy fit toutes les remonstrances qui luy femblèrent et très requises &amp; à propos, pour le persuader de venir à ladite Treue générale. A quoi le Turc n'a jamais voulu condescendre, alléguant sur ce les raisons &amp; difficultés qui luy donnoient occasion de n'y entendre. Et entraurs qu'étant aimé &amp; prêt à faire la guerre, &amp; sur l'entrepôt de Castelnovo, où il envoyoit Barbetouffe auce 250. voiles &amp; une autre grande force par terre; il ne pouvoit honnêtement, ny raisonnablement se departir de ladite entreprise, ny par conséquent accorder la Treue générale. Outre aussi qu'il voit la Chreštientė dépourueuse, &amp; par ce moyen son entreprise plus à propos. Il est vrai comme a rapporté ledit Canteline, qu'à l'instance &amp; persuasion de Laurent Griti, ledit Turc a condescendu à prolonger aux Venitiens pour trois autres mois la Treue qu'il auoit auce eux, &amp; eftoit bruit que l'Ambasfâdeur de la Seigneurie y devoit en bref arriver pour coûter une Paix ou bien une longue Treue. Et ce qui peut confirmer cette opinion, est que passant l'Armée de Mer du Turc auprès des Ports de ladite Seigneurie, il a été visé de chaque coste de signes d'amitié &amp; d'allegresse, qui donnent grande apparence qu'il y a déjà quelque chose d'arrêté.\n\nEt pour autant que ces jours passez le Noncé du Pape à fait entendre au Roy de la part de la Sainteté, qu'on luy auoit rapporté que ledit Seigneur entretenoit toujours les Lutetiens &amp; le Roy d'Angleterre en soit amitié, &amp; que sous l'espoir qu'ils auoit de luy, ils se rendoient de tant plus duts à retourner en l'obéissance de l'Église, &amp; qu'aussi la dépêche dudit Canteline auoit été plus fondée, pour moyennner la Paix aux Veniens, &amp; en ce faisant empêcher la Treue générale ; qu'autrement : adjouvant ledit Noncé à cela, que ledit Canteline est sortir de Naples, &amp; à cette cause peut enclin à faire chose qui peut apporter vtilité audit Sr. Empereur. Ce discours a grandement déplié audit Seigneur Roy, &amp; luy déplaivoit encore plus, si l'Empereur par les aduis que l'on pouvoit luy en donner de Rome ou d'ailleurs venoit à y adjouer foy. A cette cause\n\nLa candide francisée &amp; sincérité du Roy envers l'Empereur, parroit entièrement en cette Instruction.\n\nN° 11462 LETTRES ET MEMOIRES D'ESTAT.\n\nledit Eleu priera l'Empereur de la part du Roy, de croite que comme il s'est offert liberalement à s'employer enuers le Turc pour le fait de ladite Treue, qu'il y a procédé sans feintise, ny dissimulation ; mais de bon zèle &amp; avec toute la fincérité que l'on pouvoit defter, &amp; de tant plûtost fait élection de Cantelne, qu'il penta que s'il estoit fi heureux de rapporter vne bonne résolution de la Treue, cette occasion luy pouroit grandement profiter en la restitution de ses biens de Naples. Et est à considérer que si ledit Sr. Roy eût eu le pouvoit de manier ainsi facilement le Turc, il auroit durant les grandes affaires qu'il a eués cy-deuant, comme chacun fçait, essayé beaucoup plûtost que maintenant, de tirer de luy ne bonne somme de deniers, &amp; de le rechercher de venir travailler la Chrestiente. C'est chose à quoy il ne voudroit pas seulement penser, &amp; se reconnoisstta toujours par effet, que l'intelligence que ledit Sr. a auce le Turc, ne tend à autre fin, sinon à faire bien &amp; vitilité à la Chrestiente ; quelques calomnies que l'on puisse faire au contraire, dont il fait fi peu de compte, qu'elles ne luy s'cauroient donner vne seule passion, s'achant mieux que nul autre, de quel pied il marche en ce qui concerne le bien de la Religion Chrestienne.\n\nEt s'il vient à propos de parlet du fait d'Angleterre, ledit Eleu dita que ledit Sr. Empereur peut estre affecté que le Roy n'est pour aucunement contreuenit, n'y prejudicier à ce qui en a esté dernierement conclu &amp; attesté entreux, quelques partis qui luy ayent esté iusques icy, &amp; soient par cy-apres mis en auant : car de sa part il est si seur &amp; si fermo en l'amitié qu'il porte audit Sr. Empereur son meilleur Frere, que le Duché de Milan, ny autres choses particulières ne luy pouroit faire changer d'opinion.\n\nEt ne sera obmis de dire aussi audit Sr. Empereur, que si son passage se fût addonné par la France, le Roy y eût pris plaisir, comme à l'vne des choses de ce monde que plus il desfroit ; mais puisque les affaires dudit Sr. Empereur ne le portent pas ainsi, ledit Sr. Roy est &amp; sera toujours trescontent de tout ce qui luy plaira, &amp; ne le voudra rechercher de faire plus auant que sa volonté &amp; commodité. Bien le prie que venant à passer par ses Ports, il y vse &amp; commande à ses Sujets &amp; Officiers, tout ainsi qu'il feroit aux siens propres. Et ne faudra aussi ledit Eleu d'Autanches de luy faire entendre que le Roy est deliberé d'envoyet au devant de luy ses Galères pour l'accompagner. Fait à Chantilly, le 5. d'Aoult 1639.\n\nRelation dudit Eleu d'Auranches à son retour d'Espagne en Septembre 179.\n\nL'EMPEREUR ayant entendu la charge de l'Eleu d'Auranches, &amp; ce qu'il luy a déclaré de la part du Roy, a remercié ledit Seigneur tres-affectueusement de la declaration qu'il faisoit iournellement de la bonne amitié qu'il luy porte ; disant que si ses affaires le peuvent porter, il sera tres-ais de passer par la France, auquel lieu il s'cait bien qu'il aura autant de seureté qu'en ses propres Pais, &amp; beaucoup plus de plaisir &amp; de contentement, qu'en nul autre lieu, où il pouroit arriver : mais qu'il n'estoit pas encore resolu du temps de son voyage, attendant ce que sera leLIVRE III. ANNEE M.D. XXXIX. 459\n\nTurc, &amp; encore qu'il paÿât en Italie, qu'il ne le fera que pour mettre fin à ce qui est à conclure entre le Roy &amp; luy, &amp; qu'il n'y a autre affaire quelconque ; &amp; seroit très-content s'il esttoit possible que toutes choses se peuvent vider en l'vue de ses Frontières, sans qu'il laïssait ses Royaumes, auxquels sa présence est plus que nécessaire pour le bien de ses affaires. Toutefois pour mieux vider au contentement du Roy toutes choses, qu'il luy sembloit entre requis de déloger au plutôt qu'il luy seroit possible de sesdits Royaumes, &amp; que dans le temps convenu, il propoferoit au Roy tant de bonnes choses pour le commun bien de leurs affaires, qu'il esperoit qu'elles luy satisferoient, &amp; qu'à tout le moins, il n'y auroit faute qu'il n'entretint &amp; accomplit tout ce qu'il auoit promis, si le surplus qu'il a adusifé, n'est trouvé à propos par le Roy, lequel connoisira lors &amp; louera la raison, pour laquelle ilen a vés de la force en toutes ces choses.\n\nSur ce, ledit Eleu ayant fait entendre de la part du Roy audit Sr. Empereur, que ledit Seigneur n'est aucunement passionné de la reddition du Duché de Milan, &amp; que pour dix Duchés il ne voudroit perdre son amitié ; ledit Sieur Empereur a répondu que ladite reddition estoit feure &amp; du tout conclu &amp; arrestée.\n\nEt sur ce qui luy a été déclaré de la part du Roy des propos qu'il auoit eu avec le Noncé du Pape, l'Empereur a répondu modèlement qu'il n'auoit pas entendu que le Pape eût fait porter telles paroles au Roy par son Noncé, &amp; que ce sont choses qui ne sont pas vray semblables, comme il auoit auparavant bien au long déclaré à Mr. de Tarbes, &amp; que graces à notre Seigneur, les choses estoient si bien entre le Roy &amp; luy, que telles inventions &amp; calomnies ne diminueront rien de leur amitié, mais la confirment &amp; fortifient de tant plus, que ceux qui feignent de vouloir la Paix, s'efforcent de l'interrompre, pour les causes que le Roy entendait aussi bien que luy ; &amp; que de sa part il le remercioit très-affectueusement de la peine qu'il auoit prise à moyennner la Treue envers le Turc, daurant qu'il s'ait bien que ledit Seigneur y a fait tout ce qu'il a peu, &amp; est tout certain qu'il ne rient pas le Turc en sa manche, lequel pour être Prince Barbare &amp; sans foy est mal-traitable &amp; très-difficile à luy persuader de perdre ses commodités ; attendu qu'il se voit armé &amp; est daurant plus superbe, qu'il a connu que la braverie dont vsoit la Ligue l'année passée s'est convertie en fumée &amp; que la Chrestienne est demeurée dépourvuvée de toutes choses. Que si dès le temps que le Roy s'offrait à y envoyer, l'on y eût entendu, il pensoit bien que la Treue générale eût été conclue : toutefois suivant l'offre que le Roy luy fait de s'employer envers le Turc en toutes choses qui concerneront le bien de ses affaires, si l'Armée dudit Turc que l'on estime être des là devant Castelnovo prend ladite Place ; il pourra être qu'il perifera lors pouuoit faire la Treue plus à son honneur, qu'il ne l'eust faite, lors qu'il en a été requis. Et puisqu'il a pleu au Roy offrit audit Sr. Empereur de luy faire tant de bien &amp; de plaisir, après l'auoit très-affectueusement remercié de sa bonne volonté, il le prie d'yser de la commodité qu'il aura de conduire ladite Treue envers ledit Turc. Et daurtre part, si ladite Armée470 LETTRES ET MEMOIRES D'ESTAT,\n\nvient à ne prendre Castelnouo, peut-être aussi que ledit Turc ayant tabbatu quelque chose de sa brauque entendra plus aisément à la Treue en luy rendant ledit Castelnouo, qu'il n'a fait lors qu'il a été recherché ; &amp; s'il se rend obstiné, ledit Sr. Empereur prie le Roy d'aduisir pour le bien de la Chrestienté à faire une Ligue défensive &amp; offensive, le tout sous son bon plaisir ; afin que la Chrestienté soit disposée à refuser audit Turc : &amp; que s'il plaist au Roy, il sera bon que ladite Ligue soit generale, veu qu'il leur sera d'autant plus aisé de se défendre, qu'il y aura plus de confédéréz. Et pour entendre sur ce plus amplement son intention, il nous remit à Mrs. de Cours &amp; Granuelle.",
 "\n\nLe Docteur Cehot.\n\nDes propositions de paix faites à ceux de Strafbourg de la part de l'Empereur, &amp; des résolutions des Habitants de ne rien faire au prejudice de leur Religion &amp; liberté.\n\nOrigin.\n\nSIRE, depuis deux ans en çà il y a vn certain personnage à Vlme, qui a fait refidence en cette Ville homme riche &amp; opulent, allié des Premiers du Confeil de l'Empereur nommé Rellingere, qui depuis quelques semaines en çà, s'est retiré deuers l'Empereur &amp; le Sr. de Granuelle, pour ses propres affaires. Cependant pour gratifier enuers l'Empereur &amp; monitter la volonté qu'il porte à cette République: il a fait auec Granuelle, que si cette Ville à quelqu'autre moyen &amp; meilleur accès enuers l'Empereur que les autres n'ont eu, qu'on pouroit faire tant enuers ledit Empereur qu'il ne toucheroit aucunement &amp; ne changeroit rien à leur liberté &amp; Religion, ny qu'ils ne viendroiét querit mercy comme les autres Villes ont fait, &amp; ne receutoient en leur Ville les garnisons dudit Empereur. Mais qu'ils juteroient &amp; promettroient obeir à ses commandemens, &amp; garder leur foy, comme ont fait par cy-deuant les Villes Imperiales, &amp; que doresnauant ils ne traiteroient aucune paix sans son frère Ferdinand, &amp; qu'ils payeroient amande pecuniaire: &amp; a enuoyé deux fois pour cette affaire comme nous avons écrit &amp; de son propre mouvement, sans auoir effé prié ny receu aucun commandement: Et à la fin il a effé enuoyé vn sauf-conduit sous-figné de l'Empereur, pour enuoyer Ambassadeurs deuers luy. Sur quoy le Senat a aduifé qu'il n'y auoit point de danger d'effayer ce moyen, &amp; qu'il ne feroit trouvé bon de mépriser cette occasion, &amp; pour la tierce fois effre mandez &amp; n'y faire aucune réponse; pensant aussi qu'il ne falloit refuser vne honnête condition de paix, &amp; mesmement qu'ils sont delaissez de tous, &amp; qu'ils ont eu advertisement qu'on enuoyoit des-ja gens de Chenal pour leur courir sus: &amp; pour cette cause ont effé deputez ces trois dessus nommez pour y aller, &amp; connoissre si ce que cesfuy-cy a écrit est vray, &amp; ce qu'on pourra moyenner. Aussi qu'ils n'ont pouuoit de traiter, mais ont commandement de n'accorder chose, dont ils n'ayent premierement aduerti le Senat &amp; eu leur consentement &amp; de tout le peuple: car ces jours passez les trois cens Etcheuins sont venus par deçà, &amp; ont commandé au Senat &amp; aux treize ordonnnez pour la guerre de ne conclure aucune chose sans leur consentement, &amp; que de leur part ils n'arrefferoient rien, sans auoir l'aduis du peuple. L'aduis du peuple est de ne rien faire contre les Traitez, &amp; par ce moyen le Senat ne pouuoit composer, receuoit les garnisons de l'Empereur, bailler argent, ny permettre chose dont il puisse aduenir inconuement à leur liberté &amp; Religion, sans le consentement de l'Electeur &amp; de leurs alliez, qui ont toujours demeuré en leur foy. IlsLIVRE V. ANNE'E M. D. XLVII. 619\n\nont aussi envoyé deux l'Electeur pour s'gauoir ce qu'ils auroient à faire, &amp; qu'il répondit ce que bon luy sembleroit : ce sont choses veritables que nous avons écrit, &amp; est tel l'estat du Senat. Si nous pouvons demeurer en l'etat que nous étions auparavant la guerre, nous aurons la paix; sinon, ils ont deliberé de demeurer plûtost ennemis, que de faire chose qui leur soit prejudiciable. Il nous a semblé bon d'aduertir V. M. de tout ce discours, afin de penser &amp; aduiser de bonne-heure ce qu'elle auroit à faire: si ces trois Deputez n'apportent nouvelles de quelque bonne &amp; honnête paix, on ne traitera rien: &amp; pour cette cause il faut attendre trois temps bien dangereux. L'on qu'avant que l'ennemy vienne, il est besoin de faire une dépense pour les garnisons: à quoi V. M. s'est offerte pour ledit Sr. de Mandoffé. Le second, si l'Empereur ordonne gens de Cheval pour les Villes circonnoises. Le troisième, s'il vient avec groffé Armée pour affieger cette Ville, ce qui sera mal-aisé à faire: &amp; avant que les deux derniers points aduiennent, les Noffres espèrent qu'ils pouront être secourus &amp; demandent aide, &amp; attendent de cela réponse après que V. M. aura été aduertie du rout par ledit Sr. de Mandoffé. Il y a un seul expédient pour confirmer le courage des Citoyens; c'est qu'après que leurs Deputez seront de retour, ils soient affeués que voffre secours est prêt. Cependant nous serons noffre devoir, afin de faire chose qui puisse être à voffre advantage: &amp; prions le Créateur maintenir &amp; conférer V. M. Eferit le 19. de Février 1547.\n\n",

In [9]:
cluster12_samples = (
    df.filter(pl.col("cluster1") == 12)
    .select("markdown")
    .sample(5)
    .to_series()
    .to_list()
)
cluster12_samples

["\n\nD I L E C T E fili, salutem &amp; Apostolica m benedictionem. Audito Christianiflimi Regis sapienti judicio, quo nobilitatem tuam ad supremum Regni Francie Magistratum evexit, magna profecto latitia affecti sumus. Quot viro &amp; probo, &amp; prudenti, &amp; Q. iij\n\nOriginal du 11. Mars.3\n\nLe ferey voir cyapres, par divers les Lettres, que les Papes traitent les Ducs même fou. Certains de Nobiliu vis &amp; de Nobilius.\n\nLes Eloges du Pape &amp; du Connoissable se veront cyapres.\n\nOriginal.\n\n\n\n# LETTRES ET MEMOIRES DESTAT.\n\nmultis virtutibus ornato, ex potestas accellerit, quâ &amp; rei Christianae, &amp; Apostolicae Sedis possit maiori multo auctoritate patrocinari. Qualem mentem, animum qu in omnibus actionibus suis temper ostendit. Graculamur itaq; primum Regia Majestati, quæ beneficiu dando accepit, cum digno dedit. Deinde Nobilitati tuæ, quæ tantum Principis iudicium in se promeruit. Er speramus hoc, Deo benevolente atq; auctore, factum esse, vit ea Fidelium rem atque expeditionem à nobis aduerfum Turcas fusceptam maiore suffragio valeat adiuare. Ad cuius auxilium, aut potius stabilimentum, vt Majestatem praetam, licet optime, vt credimus animatam, suis hortutibus impellere velit rogamus. Certem enim si Christianissimi Principis debitum, si veterum monumenta, &amp; maiorum gesta renoluiimus, Coronæ Francorum propria est, &amp; fuit temper, expeditiocontra Infideles. Datum Romæ apud sanctum Petrum sub annulo Pificatoris, die 12. Martij. M. D. XXXVIII. Pontificatus nostri anno quarto. FABIVS VIGIL.\n\nEt au dessus, Dilecto Filio nobili Viro Domino de Montmorandi Regni Franciæ Connoissabili.\n\n\n\n# L'ARCHEUESQUE DE BORDEAVS AV CONNESTABLE.\n\nDe quelques Lutheriens qui s'effoient retirés de Bordeaux en Languedoc, Gouvernement dudit Connoissable.\n\nMonsiègnèvr, il est depuis demy an en ça venu vn Prefcheur en cette Ville, qui a été logé en l'Abbaye sainte Croix, qui est lieu écarté comme sauvé, &amp; loing de celuy où les gens de sauroit habitent, lequel sous ombre de ses prédications &amp; lectures a secrètement par les maisons &amp; copagnies privées semé beaucoup d'erreurs &amp; propositions damnées devant que l'on s'en soit apperceu, tellement que plusieurs jeunes Épôliers &amp; gens de bas est ont été signalés par l'ay, qu'ils adheroient totalement à l'opinion des Lutheriens lequel Prefcheur est ant aduerty que Messieurs de la Cour de Parlement &amp; mes Officiers estoient après pour le constituer prisonnier, s'est sauvé de nuit, &amp; à ce que j'entends retiré en voître gouvernement de Languedoc.\n\nMonseigneur, incontinent après avoir été aduerty de ce que dessus, &amp; que j'ay estimé cette frontière hors de danger &amp; surprise, par la présence du Roy de Navarre, aucuns de ladite Cour de Parlement &amp; moy sommes continuellement après à faire procès à ceux que trouvons entre chargés, &amp; espérons éteindre pour cette fois l'impression &amp; erreurs dudit Prefcheur, &amp; pour l'advenir serait grandement requis avoir vue Bulle du Pape semblable à celle que le feu Pape Clement fit dépêcher à Marseille, pour préférer en terme à ceux qui pourroient être dévoyés de la foi &amp; constitutions de l'Église, pour abjurer &amp; revenir à nous, car autrement est à craindre que les susdits &amp; autres tôbent en semblables erreurs, je suis assuré que qui n'aura ladite Bulle, ils seront à toute heureLIVRE II. ANNÉE M. D. XXXVIII. 87\n\nadmis, faisons semblant de se repentir &amp; abjurants : à quoy je vous supplie très-humblement, Monseigneur, tenir main, &amp; encore que ladite Cour de Parlement ayt bien fait son devoir jusqu'à présent, faire que le Roy leur écrire de me faire en cet endroit toute la faveur &amp; ayde qu'il leur sera possible, &amp; sans épargner aucun de quelque effet ou condition qu'il puisse être, &amp; à moy semblablement ; car lesdites Lettres profiteront beaucoup pour tenir les gens en crainte.\n\nMonseigneur, Moniteur de Tarbes mon Neveu m'a écrit, que vous luy aués dit que vous me feriés acquitter par le Roy le don gratuit équipolant à trois décimes, dont très-humblement vous remercie, vous admis, Monseigneur, que ne s'gauriés ce faire à personne, qui plus vous voulaît faire service, ne qui ayt meilleur besoin d'être aydé &amp; secouru que moy, veu les grands frais &amp; mises qu'il m'a convenu &amp; convient faire journellement pour le service dudit Seigneur.\n\nMonseigneur, je prie le Créateur qu'il vous doint en santé très-longue vie. A Bordeaux ce 12. jour de Mars.\n\nVous fériés beaucoup pour le service de Dieu &amp; du Roy, si c'estoit votre plaisir écrire à Môseur le Senechal de Toulouse votre Lieutenant, qu'il s'est costituit prisôniers ceux qui se sont retirés audit Toulouse &amp; ailleurs en votre Gouvernement, contre lesquels les informations, ou captatur des Commissaires de la Cour &amp; de moy luy sont envoyés.\n\nVotre très-humble &amp; très-obéissant serviteur\n\nC. DE GRAMONT Arch. de Bordeaux;\n\nEt au dessus, A Monseigneur, Monseigneur le Connestable.",
 "\n\nCe Sieur de Granuelle, avec lequel l'Ambassadeur auoit tant de communications &amp; de confiance, s'appelloit Nicolas Perenot, surnommé de Granuelle, à cause d'une terre Seigneuriale de ce nom, qu'il auoit acquise. Il estoit lors de cette dernière Lettre, Chancelier &amp; premier Secrétaire de l'Empereur, &amp; en plus grand crédit, authorisé &amp; confidence auprès de luy, que nul autre ; ayant en cela succédé au Cardinal Mercurain Gattinare, qui durant sa vie estoit le Confidentissime. Ce fut par son excellent esprit, que Granuelle s'éteva ainsi : car il estoit de basse naissance, &amp; selon quelques Historiens, fils d'un Maréchal de forge, ou Servierier dans Bezançon, au Comté de Bourgogne. Son Père le voyant d'esprit qui promestoit beaucoup, prit soin de luy faire apprendre à bien lire &amp; écrire ; puis le mit Clerc chez un Procureur, où il se rendit si bon Praticien, que le Chancelier de Bourgogne l'ayant pris en estime, le donna pour Secrétaire à Madame Marguerite d'Autriche, Duchesse douairière de Savoye, Tante de l'Empereur, lequel depuis le désira pour l'y-même, &amp; en fit après quelque temps de service\n\nStrada, Aubery &amp; autres.LIVRE III. ANNÉE M. D. XXXIX. 371\n\nnon seulement son premier Secrétaire d’un Chanceller, mais son première principal Ministre d’Etat. Aussi étroit-il sort efflairé, prudent et judicieux, même très-modéré pacifique en ses conseils et négociations, concernant les troubles des nouvelles Sectes d’Allemagne, car un de ces nouveaux religionnaires des plus effimes, parmi eux rapportés, que Granuelle défait tellement la Paix et la tranquillité entre les Catholiques et les protestants, que ce fut lui qui s’éteint, disposait d’Empereur en 1340 à la vouloir bien aussi. Il mourut en 1350 après avoir eu, dit le même Historien, la connaissance presque lui seul des sécrecs du profond du cœur de son Prince l’espace de vingt ans. Mais ce qui est encore plus merveilleux, c’est d’avoir laissé sa direction des affaires d’Etat aussi l’affection, créance et confiance entière, qu’avait l’Empereur en lui, à Antoine de Granuelle son fils, comme si elles eussent été héréditaires. Il avait par prévoyance et penetration de l’avenir, si bien élevé, instruit et exercé sous lui ce fils, qu’il s’était rendu capable du Ministère d’infinue aux bonnes grâces de l’Empereur, qui le prit depuis en telle estime, qu’en rejoignant ses États à Philippe II. Son fils, il lui conseilla de faire Antoine de Granule, lors Ensigne d’Arras, son premier Ministre : conseil que le Roy Philippe faisait ponctuellement, qu’il pourra ensuite la pourpre et dignité de Cardinal.\n\nM. de Thun, I.6 le qualité versus magnapandentia.\nSindon list. 12 vers la fin.",
 "\nL'éloge du Sieur Card. se verra cyapera, duquel cy. deuant p. 171. &amp; 1. Origin.\n\nLettre de remerciement &amp; compliment du Cardinal Farnese, il est fait petit fils du Pape Paul III.\n\nMONSEIGNOR, oltre l'obligazioni ch'io ho, &amp; debbo hauere à V. Excellentia, per li continui meriti, &amp; bone opere sue verso N. S. questa sancta Sede &amp; tutta Christianita, me fa aggiunge anche nouamenté questa particolare della cura che si è degnata pigliare della mia spedizione d'Altacomba, hauendo promesso à Mons. d'Yurea di farla fare come la Corte giunge a Parigi, Di che certo ho pigliato infinito piacere, non tanto per l'interesse del negocio, delquale, per le manifeste ragioni mie, non ho mai sperato altro fine dalla bona iustizia di corretto Regno, Quanto per la stima che io faccio, che si conosca, che l'Excellentia V. tenga memoria di me, &amp; che la feruica, &amp; affettione singolare ch'io porto alla Majesta del Re, &amp; a lei sia hausta in qualche considerazione. Glie ne rendo dunque quelle gracie che io posso maggiori.\n\nC'estoit le Nonce du Pape en France.LIVRE II. ANNEE M. D. XXXVIII. 239\nDECEMBRE.\n\nmaggiori, &amp; la prego per l'effetto del negocio quartilo fara tempo, che per la causa fopradetta mi fara di molto fauote &amp; gratia; Nel refto fupplita Monsegnor d'Yurea, alquale mi rimetto. Raccomandandomi di continuo à V. Excellentia, &amp; pregandola à degnarfi di far le mie humilimi raccomandationi alla bona gratia di fua Majesta &amp; delii ferenissimi figli miei fignori, che Dio li conferui tutti in longa &amp; felice vita. Di Roma alli 3. di Decembre 1338. Plus bas, D. V. Excellentia fengitore il Card. FARNÆZ. Au dessus, Al III. &amp; Excell. Segnor Monsegnor il Consistabile di Francia.\n\n",
 "\n\nLe Maréchal de Montejan Lieutenant du Roy en Piémont l'ay donne aduis de la necessité des viures, &amp; de l'ordre qu'il tient pour régler les confins entre le Roy &amp; l'Empereur.\n\nMonseigneur, vous aues bien amplement entendu par le general de Bretagne l'esrar &amp; dispose de par deca, à quoy est requis &amp; necessaire de pournoir, messement au paiement des Lansqueners dont ie vous ay tant de fois écrit, &amp; pareillement à celuy des gens de pied François qui echet le premier jour d'Avril, lesquels j'ay tous reduits dedans les Villes où il ne leur est possible de pouuoir viure sans estre payés pour la grande cherte des viures qui y est &amp; la difficulté d'y en faire amener; c'est vne des choses dont nous avons plus de besoin pour cette heure : à cette cause ie vous supplie, Monseigneur, y vouloir donner ordre, &amp; en ce faisant vous pouués estre afeuré que vous ferés hors de peine du coste de deca, ie vous pensois enuoyer Monseigneur de Langey pour plus amplement vous en aduertir, mais j'ay receu Lettres de l'Eusque de Cazal par lesquelles il m'a mande comme il s'en vient accompagne des Sieurs de Senchir Brauo, Ican de Vergaye, le Vittarin, &amp; du Sieur Benere, en cette Ville de Montcallier pour vuider &amp; conclure tous les differents &amp; occurrences qui pourroient estre faits à la Treve, touchant les confins du Roy &amp; de l'Empereur, où la presence dudit Sieur de Langey est merucilleusement requise pour debattre les choses avec eux en ce qui touche l'interest &amp; service dudit Seigneur, afin que d'iey en auant il n'en puisse arriuer inconvenient, &amp; que chacun scache &amp; entende ce qu'il aura à faire : cependant le Sieur d'Assier present porteur s'en va en qui ie remets le surplus, vous suppliant, Monseigneur, le vouloir croire, &amp; me tenir toujours en voître bonne grace tres-humble &amp; recommandé, priant Dieu vous donner, Monseigneur, bonne &amp; longue vie. A Montcallier le vingt-sixième jour de Mars.\n\nDepuis ces Lettres écrites ie me suis aduisé de ne faire venir les Députés du Marquis de Gaast en cette Ville, pour plusieurs raisons, &amp;138 LETTRES ET MEMO IRES D'ESTAT;\n\nd'envoyer Monfleur de Languy parler à eux à Paris, afin qu'ils ne connoissent rien de nos viures ni de nos fortifications lesquelles je vous assure encore un coupÊtre telles qu'il ne nous fera point de mal, moyennant qu'il vous plâse nous envoyer des vitres. Voître très-humble &amp; très-obéissant serviteur MONTIJAN.\n\nMonfeigneur, vous fœtiez comme le Seigneur Jean-Paule a-t-oujours été par déça, &amp; me semble que feriés merutelleusement bien de luy faire écrire une bonne Lettre du contentement qu'a le Roy du feruice qu'il fait : aussi Monfeigneur, je ne veux oublier à vous ramenteuoir qu'il vous plâse m'accorder le Committé des guetres, dont je vous ay cy-deuant écrit, &amp; de plus en plus m'obligéte à vous faire feruice ; car cela me fera un grand foulagement pour la fiance que j'ay en luy.\n\nEt au dessus, A Monfeigneur, Monfeigneur le Conneitable.\n\nRemarques touchant ledit Sieur Montejan.\n\nLe choix des Committéistes de guerre ne dépend pas des Lieutenants de Roy en ses Armées &amp; Proustes\n\nEn Son Recueil des Maréchaux de France.\n\nLire 8. de ses Mémoires.\n\nLe Sieur Godefroy le nomme &amp; qualifie R en Sieur de Montejan au pays d'Anjou, Baron de Sille &amp; de Beaupreau, Gouverneur &amp; Lieutenant général du Roy en Piémont, &amp; aquoite qu'il recevra le Baron de Maréchal de France en 1330. en quoi il y a une erreur notable, laquelle j'astrebur p'utost à l'imprimeur qu'à l'Auteur même dudit Recueil, qui a été très-oxaÃ§ &amp; judicieux en tous ses Ecrits : il est certain que ledit Seigneur de Montejan ne fut Maréchal de France qu'en 1337. comme on composa lors, parce que l'année ne satisfait qu'à Pafques ou en 1338. selon notre compte préféré : j'ay pour macaution entre-autres Historiens le Seigneur de Languy, G. du Bellay qui dit affirmativement qu'après la Trêve d'Italie faite entre le Roy &amp; l'Empereur &amp; publiée en Novembre 1337. le Roy qui avait passé les Monts voulant recuser en France pourueur auparavant par sa prudence aux affaires du Piémont, &amp; y établit le Seigneur de Montejan Gouverneur &amp; Son Lieutenant Général, puis sa Majesté étant de retour en Son Royaume &amp; voulant reconnaître dignement ceux qui l'avaient bien servu dans les guerres précédentes, honora le grand Maître de Montmorency de l'Office de Conneitable en 1338. &amp; donna le sien de Maréchal de France au dit Sieur de Montejan ; cet Autre urêt d'autant plus croyable parce qu'il servait le Roy sous Montejan dans le Piémont en qualité de Gouverneur particulier de Turin, &amp; même ils eurent quelque différent, comme on verra cy-après, pour l'exercice &amp; autorité de leurs charges. Ledit Seigneur de Montejan passé dans toutes nos Histoires pour un bard &amp; très-bazardieux Chevalier, il fut du nombre des préveniers de marque dans la malheureuse &amp; funeste journée de Paris, &amp; depuis encore en la guerre de Provence en 1338. Tuy &amp; Boisy tous deux Chevaliers de l'Ordre &amp; commandants chacun une Compagnie de cinquante hommes d'armes furent pris par les ennemis pour l'être trop auanturés &amp; avancés sur le dessein qu'ils avaient des surprendre Dom Ferrand de Gonzague qui menait l'avantgarde de l'Empereur. Cette disgrace de Montejan chef de l'entreprise ne l'éloigna point des bonnes graves du Roy &amp; de l'efdime qu'il faisait de son courage, mais sa Majesté n'en fut pas longuement servie depuis qu'il fut son LieutenantLIVRE II. ANNE'E M. D. XXXVIII. 139\n\nen Piémont et Maréchal de France; car il mourut selon nos Historiens dès l'année 1138. Et selon la pure vérité en l'année suivante seulement, comme le vérifira clairement par une Lettre originale que j'ay de sa main du mois de May 1139, qui sera mise en son ordre.\n\nIl portait d'oe fetté de goreau.\n\n",
 "\n\nLe Seigneur de la Cra on des Confidens du Duc de Sauoye, représente la sincere affection qu'a son Duc envers le Roy; que sa MaieSté a interreff de confermer &amp; maintenir cette maison; que Nice est ville de conséquence, que le St. Suaire y est, &amp; les principaux titres, joyaux &amp; meubles de Sauoye.\n\n### Origin.\n\nMONSEIGNEVR, depuis mes dernières lettres, Monfieur de Sauoye s'est trouvé trois ou quatre iours mal à son aife, chose qui luy aduient fouuent depuis quelque temps en ça. Surquoy me trouvant auec l'homme affectionné que vous connoissés, il m'a commencé des propos des inconueniens qui poutoient aduenit, si noître Seigneur prenait à foy mondit Sieur de Sauoye, &amp; des dangers où pouroit tomber Monfieur le Prince son fils estant en si bas âge, veu que tous ceux qui sont aupres de luy, sont à la deuotion de l'Empereur. Pareillement en quelles mains pouroit venir cette maison qui est de la conséquence que vous fçavez; ensemble les meubles qui y sont dedans, à fçauoir le St. Suaire, la plus-part des principaux titres de la maison de Sauoye, qui peuvent grandement feruir au Roy &amp; ses successeurs, &amp; plusieurs autres choses, comme tapisseries &amp; pierreries, qui ne sont de petite importance estans sous la chatge du susdit, dont aduenant tel cas de mort, mondit Sieur le Prince, le peu de reste qu'il a de son estat, ensembleLIVRE III. ANNE'E M. D. XXXIX. 409\n\ncette maifon &amp; le tout que dessus, féroit en grand danger de tomber en totale tuine : tellement qu'il y auroit bien peu d'effperance d'y pouvoir remedier pour l'advenir ; veu metmement le mauvais confeil qui est ivv, la mauvaise volonré des voifins, qui font les Geneuois qui ne t'aflent iournelement que de surprendre cette maifon. A l'occasion de quoy ledit perlonnage m'a prié de vous vouloir eferire &amp; aduertir des chofes fufdites, à ce qu'il vous plaife y aduifer : comme s'il vouloit dire par refolution, qu'il pleiât au Roy d'vfer enuers mondit Sieur de Sauoye, de sa liberalité accouftumée, &amp; de venir à quelque party raisonnable : de forte que mondit Sieur de Sauoye, &amp; ses sujets foyent gaignez perpetuellement pour le feruice du Roy &amp; ses successeurs ; me faifant entendre que tout cela se peut aifement reduire par voître moyen. Je vous puis bien affeurer, Monfeigneur, que ledit homme n'en parle que pour l'affection &amp; bonne volonté qu'il a d'estre perpetuel feruiteur du Roy, &amp; sur tous les propos qu'il m'a tenu en cet endroit, je ne puis confiderer ny connoisse qu'ils viennent d'autre lieu, que de la part de mondit Sieur de Sauoye son Maifre.\n\nMonfeigneur, ledit homme m'a dit en outre que depuis trois jours, il luy a efté faite quelque ouverture, d'où procede la pratique de Cefar Duc ; &amp; dedans peu de jours, il m'en fera entendre la verité pour le vous faire feauoir, afin que vous ayés pleine connoissance, que mondit Sieur de Sauoye ny eft en rien compris, mais eft vne chofe controuvée, pour donner ennuy à beaucoup de gens sans occasion, &amp; aujourd'hui mefmes mondit Sieur de Sauoye m'en a tenu propos, qui fait ainsi qu'il dit, tout ce qui luy eft possible pour en feauoir la verité, &amp; vous en aduertir. De Nice ce 16. Mars 1539. Voître tres-humble &amp; tres-obéissant feruiteur."]

In [7]:
from clustering.clustering import create_cluster
import polars as pl

folder = "ribier_v1"

df1 = pl.read_parquet(f"./books_work/{folder}/data/{folder}_chunked.parquet")
docs = df1["embedding"].to_list()
cluster3, soft3, samples3, iters3 = create_cluster(docs, run_num=1, soft_assign=False)
cluster4, soft4, samples4, iters4 = create_cluster(docs, run_num=2, soft_assign=False)
df1 = df1.with_columns(cluster3=pl.Series(cluster3), cluster4=pl.Series(cluster4))
print("Cluster 3:")
with pl.Config(tbl_rows=25):
    display(df1["cluster3"].value_counts().sort("cluster3"))
print("Cluster 4:")
with pl.Config(tbl_rows=25):
    display(df1["cluster4"].value_counts().sort("cluster4"))

  Estimated number of clusters: 14
  Restart 1/10 (seed 10) — score: 0.9402
  Restart 2/10 (seed 11) — score: 0.9400
  Restart 3/10 (seed 12) — score: 0.9403
  Restart 4/10 (seed 13) — score: 0.9403
  Restart 5/10 (seed 14) — score: 0.9398
  Restart 6/10 (seed 15) — score: 0.9402
  Restart 7/10 (seed 16) — score: 0.9404
  Restart 8/10 (seed 17) — score: 0.9399
  Restart 9/10 (seed 18) — score: 0.9401
  Restart 10/10 (seed 19) — score: 0.9393
  Best score: 0.9404
  Estimated number of clusters: 14
  Restart 1/10 (seed 20) — score: 0.9406
  Restart 2/10 (seed 21) — score: 0.9400
  Restart 3/10 (seed 22) — score: 0.9396
  Restart 4/10 (seed 23) — score: 0.9399
  Restart 5/10 (seed 24) — score: 0.9401
  Restart 6/10 (seed 25) — score: 0.9394
  Restart 7/10 (seed 26) — score: 0.9403
  Restart 8/10 (seed 27) — score: 0.9402
  Restart 9/10 (seed 28) — score: 0.9386
  Restart 10/10 (seed 29) — score: 0.9399
  Best score: 0.9406
Cluster 3:

shape: (14, 2)
┌──────────┬───────┐
│ cluster3 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 75    │
│ 1        ┆ 21    │
│ 2        ┆ 17    │
│ 3        ┆ 78    │
│ 4        ┆ 6     │
│ 5        ┆ 26    │
│ 6        ┆ 23    │
│ 7        ┆ 9     │
│ 8        ┆ 3     │
│ 9        ┆ 28    │
│ 10       ┆ 42    │
│ 11       ┆ 54    │
│ 12       ┆ 24    │
│ 13       ┆ 7     │
└──────────┴───────┘

Cluster 4:

shape: (14, 2)
┌──────────┬───────┐
│ cluster4 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 28    │
│ 1        ┆ 65    │
│ 2        ┆ 19    │
│ 3        ┆ 9     │
│ 4        ┆ 23    │
│ 5        ┆ 6     │
│ 6        ┆ 37    │
│ 7        ┆ 68    │
│ 8        ┆ 11    │
│ 9        ┆ 78    │
│ 10       ┆ 8     │
│ 11       ┆ 14    │
│ 12       ┆ 25    │
│ 13       ┆ 22    │
└──────────┴───────┘

In [11]:
df.sample(5)

shape: (5, 12)
┌───────────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬──────────┬──────────┐
│ letter_id ┆ id    ┆ title       ┆ pdf_pages  ┆ … ┆ full_markd ┆ embedding  ┆ cluster1 ┆ cluster2 │
│ ---       ┆ ---   ┆ ---         ┆ ---        ┆   ┆ own        ┆ ---        ┆ ---      ┆ ---      │
│ u32       ┆ u32   ┆ str         ┆ list[i64]  ┆   ┆ ---        ┆ list[f64]  ┆ i64      ┆ i64      │
│           ┆       ┆             ┆            ┆   ┆ str        ┆            ┆          ┆          │
╞═══════════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪══════════╪══════════╡
│ 10129     ┆ 10129 ┆ APOLOGIE    ┆ [327, 328, ┆ … ┆            ┆ [-0.043457 ┆ 8        ┆ 11       │
│           ┆       ┆             ┆ … 356]     ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ des permis ┆ -0.029053, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ sions de   ┆ … -0.01…   ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ Duel obte… ┆            ┆          ┆          │
│ 10082     ┆ 10082 ┆ LA CHAMBRE  ┆ [226, 227] ┆ … ┆            ┆ [-0.014221 ┆ 12       ┆ 8        │
│           ┆       ┆ DES         ┆            ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆ COMPTES.    ┆            ┆   ┆ Elle       ┆ -0.008301, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ depute     ┆ … -0.02…   ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ tant vers  ┆            ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ le Roy…    ┆            ┆          ┆          │
│ 10050     ┆ 10050 ┆ AVDIT       ┆ [174]      ┆ … ┆            ┆ [-0.025146 ┆ 4        ┆ 0        │
│           ┆       ┆ CONNESTABLE ┆            ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ J. Jacques ┆ -0.019775, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ Castron    ┆ … 0.001…   ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ Commis à … ┆            ┆          ┆          │
│ 10022     ┆ 10022 ┆ AVTRES      ┆ [82, 83, … ┆ … ┆            ┆ [-0.032715 ┆ 4        ┆ 11       │
│           ┆       ┆ ARTICLES    ┆ 85]        ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆ DÉBATTVS    ┆            ┆   ┆ en ladite  ┆ 0.003464,  ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ communicat ┆ … 0.0058…  ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ ion non …  ┆            ┆          ┆          │
│ 10271     ┆ 10271 ┆ CAROLVS.    ┆ [568]      ┆ … ┆            ┆ [-0.048584 ┆ 1        ┆ 2        │
│           ┆       ┆             ┆            ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆            ┆ -0.026123, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆            ┆ … -0.03…   ┆          ┆          │
└───────────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴──────────┴──────────┘

shape: (5, 13)
┌───────────┬───────┬─────────────┬────────────┬───┬────────────┬──────────┬──────────┬────────────┐
│ letter_id ┆ id    ┆ title       ┆ pdf_pages  ┆ … ┆ embedding  ┆ cluster1 ┆ cluster2 ┆ subcluster │
│ ---       ┆ ---   ┆ ---         ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ 1          │
│ u32       ┆ u32   ┆ str         ┆ list[i64]  ┆   ┆ list[f64]  ┆ i64      ┆ i64      ┆ ---        │
│           ┆       ┆             ┆            ┆   ┆            ┆          ┆          ┆ null       │
╞═══════════╪═══════╪═════════════╪════════════╪═══╪════════════╪══════════╪══════════╪════════════╡
│ 10262     ┆ 10262 ┆ AV CARDINAL ┆ [554]      ┆ … ┆ [-0.047852 ┆ 12       ┆ 8        ┆ null       │
│           ┆       ┆ DV BELLAY.  ┆            ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ -0.026733, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … 0.021…   ┆          ┆          ┆            │
│ 10292     ┆ 10292 ┆ GOSTAVVS.   ┆ [592, 593, ┆ … ┆ [-0.044434 ┆ 13       ┆ 8        ┆ null       │
│           ┆       ┆             ┆ … 595]     ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ -0.009094, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … -0.02…   ┆          ┆          ┆            │
│ 10009     ┆ 10009 ┆ PAVLVS PAPA ┆ [46]       ┆ … ┆ [0.00531,  ┆ 11       ┆ 6        ┆ null       │
│           ┆       ┆ III.        ┆            ┆   ┆ 0.01001, … ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ -0.019653… ┆          ┆          ┆            │
│ 10029     ┆ 10029 ┆ REMARQUES   ┆ [116, 117, ┆ … ┆ [-0.001022 ┆ 9        ┆ 7        ┆ null       │
│           ┆       ┆ SVR LEDIT   ┆ … 120]     ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆ SIEVR       ┆            ┆   ┆ -0.030273, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … 0.020…   ┆          ┆          ┆            │
│ 10006     ┆ 10006 ┆ ENSVIT      ┆ [27, 28, … ┆ … ┆ [-0.039062 ┆ 12       ┆ 11       ┆ null       │
│           ┆       ┆ LEDIT       ┆ 39]        ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆ PLAIDOYE.   ┆            ┆   ┆ -0.052002, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … -0.03…   ┆          ┆          ┆            │
└───────────┴───────┴─────────────┴────────────┴───┴────────────┴──────────┴──────────┴────────────┘