In [1]:
from clustering.clustering import create_cluster
import polars as pl
from genai.mistral import get_mistral_cluster_tags, ClusterWithTags
import time

folder = "ribier_v1"

df = pl.read_parquet(f"./books_work/{folder}/data/{folder}.parquet")
docs = df["embedding"].to_list()
print("Creating clusters...")
cluster, soft, samples, iters = create_cluster(docs, run_num=1)
df = df.with_columns(
    pl.Series("cluster", cluster),
    pl.Series("soft_cluster", soft),
)

print(f"Clustered into {len(set(cluster))} clusters in {iters} iterations.")

print("Getting tags for clusters...")

# Now let's get the cluster tags for the main clusters using Mistral
sample_docs: list[ClusterWithTags] = [
    ClusterWithTags(label=i, tags=df[s].select("markdown").to_series().to_list())
    for i, s in enumerate(samples)
]

res = get_mistral_cluster_tags(sample_docs)
res_dict = {item.label: ", ".join(item.tags) for item in res}
res_list = [res_dict.get(c) for c in cluster]
df = df.with_columns(pl.Series("cluster_tags", res_list))

print(
    "Done getting cluster tags. Now calculating sub-clusters for clusters with enough samples..."
)


print("Calculating cluster counts and percentages...")
n = len(df)
cluster_counts = df["cluster"].value_counts().sort("cluster")
cluster_counts = cluster_counts.with_columns(cluster_perc=cluster_counts["count"] / n)
clusters_to_sub_df = cluster_counts.filter(pl.col("count") ** (1 / 3) >= 3)
clusters_to_sub = clusters_to_sub_df["cluster"].to_list()
df = df.with_columns(sub_cluster=pl.lit(-1).cast(pl.Int64))
df = df.with_columns(sub_labels=pl.lit(None).cast(pl.List(pl.Utf8)))

print(f"Clusters to sub-cluster: {clusters_to_sub}")
# Let's get sub-clusters for clusters that have enough samples, and get their tags using Mistral
for c in clusters_to_sub:
    cluster_count = clusters_to_sub_df.filter(pl.col("cluster") == c)["count"][0] ** (
        1 / 3
    )
    parent_cluster_labels = res_dict.get(c)
    cluster_count = int(cluster_count)
    sub_df = df.filter(pl.col("cluster") == c)
    sub_docs = sub_df["embedding"].to_list()
    sub_cluster, _, sub_samples, iter = create_cluster(
        sub_docs, run_num=1, soft_assign=False, num_clusters=cluster_count
    )
    print(f"Sub-cluster {c} created with {iter} iterations.")
    # Get sub-cluster tags using Mistral
    print(f"Getting tags for sub-cluster {c}...")
    sample_docs: list[ClusterWithTags] = [
        ClusterWithTags(label=i, tags=df[s].select("markdown").to_series().to_list())
        for i, s in enumerate(sub_samples)
    ]
    res = get_mistral_cluster_tags(
        sample_docs, is_sub_cluster=True, parent_cluster_labels=parent_cluster_labels
    )
    sub_samples_dict = {item.label: ", ".join(item.tags) for item in res}
    sub_samples_list = [sub_samples_dict.get(c) for c in sub_cluster]

    # Assign sub_cluster to sub_df
    sub_df = sub_df.with_columns(pl.Series("sub_c", sub_cluster))
    sub_df = sub_df.with_columns(pl.Series("sub_s", sub_samples_list))

    df = df.join(
        sub_df.select(["chunk_id", "sub_c", "sub_s"]), on="chunk_id", how="left"
    )
    df = df.with_columns(
        sub_cluster=(
            pl.when(pl.col("sub_c").is_not_null())
            .then(pl.col("sub_c"))
            .otherwise(pl.col("sub_cluster"))
        ),
        sub_labels=(
            pl.when(pl.col("sub_s").is_not_null())
            .then(pl.col("sub_s"))
            .otherwise(pl.col("sub_labels"))
        ),
    )
    df = df.drop("sub_c")
    df = df.drop("sub_s")
    # If you want to fill nulls with a default value (e.g., -1), uncomment:
    df = df.with_columns(pl.col("sub_cluster").fill_null(-1))


df.write_parquet(f"./books_work/{folder}/data/{folder}.parquet")
df

Creating clusters...
  Estimated number of clusters: 14
  Restart 1/10 (seed 10) — score: 0.9375
  Restart 2/10 (seed 11) — score: 0.9371
  Restart 3/10 (seed 12) — score: 0.9384
  Restart 4/10 (seed 13) — score: 0.9376
  Restart 5/10 (seed 14) — score: 0.9375
  Restart 6/10 (seed 15) — score: 0.9376
  Restart 7/10 (seed 16) — score: 0.9374
  Restart 8/10 (seed 17) — score: 0.9372
  Restart 9/10 (seed 18) — score: 0.9374
  Restart 10/10 (seed 19) — score: 0.9379
  Best score: 0.9384
Clustered into 14 clusters in 15 iterations.
Getting tags for clusters...
Using Mistral model: mistral-large-latest. Instituting a delay of 4 seconds between API calls to avoid rate limits.
Done getting cluster tags. Now calculating sub-clusters for clusters with enough samples...
Calculating cluster counts and percentages...
Clusters to sub-cluster: [0, 2, 12]
  Restart 1/10 (seed 10) — score: 0.9430
  Restart 2/10 (seed 11) — score: 0.9426
  Restart 3/10 (seed 12) — score: 0.9433
  Restart 4/10 (seed 13) — score: 0.9434
  Restart 5/10 (seed 14) — score: 0.9431
  Restart 6/10 (seed 15) — score: 0.9437
  Restart 7/10 (seed 16) — score: 0.9442
  Restart 8/10 (seed 17) — score: 0.9430
  Restart 9/10 (seed 18) — score: 0.9435
  Restart 10/10 (seed 19) — score: 0.9423
  Best score: 0.9442
Sub-cluster 0 created with 4 iterations.
Getting tags for sub-cluster 0...
Using Mistral model: mistral-large-latest. Instituting a delay of 4 seconds between API calls to avoid rate limits.
  Restart 1/10 (seed 10) — score: 0.9470
  Restart 2/10 (seed 11) — score: 0.9469
  Restart 3/10 (seed 12) — score: 0.9465
  Restart 4/10 (seed 13) — score: 0.9466
  Restart 5/10 (seed 14) — score: 0.9466
  Restart 6/10 (seed 15) — score: 0.9463
  Restart 7/10 (seed 16) — score: 0.9458
  Restart 8/10 (seed 17) — score: 0.9468
  Restart 9/10 (seed 18) — score: 0.9463
  Restart 10/10 (seed 19) — score: 0.9471
  Best score: 0.9471
Sub-cluster 2 created with 4 iterations.
Getting tags for sub-cluster 2...
Using Mistral model: mistral-large-latest. Instituting a delay of 4 seconds between API calls to avoid rate limits.
  Restart 1/10 (seed 10) — score: 0.9466
  Restart 2/10 (seed 11) — score: 0.9452
  Restart 3/10 (seed 12) — score: 0.9461
  Restart 4/10 (seed 13) — score: 0.9462
  Restart 5/10 (seed 14) — score: 0.9463
  Restart 6/10 (seed 15) — score: 0.9467
  Restart 7/10 (seed 16) — score: 0.9457
  Restart 8/10 (seed 17) — score: 0.9463
  Restart 9/10 (seed 18) — score: 0.9462
  Restart 10/10 (seed 19) — score: 0.9462
  Best score: 0.9467
Sub-cluster 12 created with 4 iterations.
Getting tags for sub-cluster 12...
Using Mistral model: mistral-large-latest. Instituting a delay of 4 seconds between API calls to avoid rate limits.

shape: (338, 14)
┌───────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ letter_id ┆ id   ┆ markdown   ┆ pdf_pages  ┆ … ┆ soft_clust ┆ sub_cluste ┆ sub_label ┆ cluster_t │
│ ---       ┆ ---  ┆ ---        ┆ ---        ┆   ┆ er         ┆ r          ┆ s         ┆ ags       │
│ u32       ┆ u32  ┆ str        ┆ list[i64]  ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆      ┆            ┆            ┆   ┆ list[i64]  ┆ i64        ┆ str       ┆ str       │
╞═══════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 10000     ┆ 1000 ┆ LE PAPE    ┆ [46]       ┆ … ┆ [10]       ┆ -1         ┆ null      ┆ PapalDipl │
│           ┆      ┆ PAVL III.  ┆            ┆   ┆            ┆            ┆           ┆ omacy,    │
│           ┆      ┆ AV ROT     ┆            ┆   ┆            ┆            ┆           ┆ Ecclesias │
│           ┆      ┆ FRANC…     ┆            ┆   ┆            ┆            ┆           ┆ tical…    │
│ 10001     ┆ 1001 ┆ LETTRE DE  ┆ [46, 47]   ┆ … ┆ [2, 9, 12] ┆ 2          ┆ PapalMedi ┆ PapalDipl │
│           ┆      ┆ MONLVC AV  ┆            ┆   ┆            ┆            ┆ ationTact ┆ omacy,    │
│           ┆      ┆ CARDINAL   ┆            ┆   ┆            ┆            ┆ ics,      ┆ HighPolit │
│           ┆      ┆ D…         ┆            ┆   ┆            ┆            ┆ Strateg…  ┆ icalC…    │
│ 10002     ┆ 1002 ┆ LETTRE DES ┆ [47, 48]   ┆ … ┆ [2, 9, 12] ┆ 2          ┆ Diplomati ┆ Diplomati │
│           ┆      ┆ AVOTERS ET ┆            ┆   ┆            ┆            ┆ cTerritor ┆ cCorrespo │
│           ┆      ┆ CONSEILL…  ┆            ┆   ┆            ┆            ┆ ialDisput ┆ ndence,   │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ es,…      ┆ Roya…     │
│ 10003     ┆ 1003 ┆ REMARQUES  ┆ [48, 49, … ┆ … ┆ [8]        ┆ -1         ┆ null      ┆ Diplomati │
│           ┆      ┆ SVR LADITE ┆ 54]        ┆   ┆            ┆            ┆           ┆ cAlliance │
│           ┆      ┆ VILLE DE … ┆            ┆   ┆            ┆            ┆           ┆ Negotiati │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆           ┆ ons…      │
│ 10003     ┆ 1003 ┆ Cethol.    ┆ [48, 49, … ┆ … ┆ [10, 13]   ┆ -1         ┆ null      ┆ PapalDipl │
│           ┆      ┆ 1192. 6    ┆ 54]        ┆   ┆            ┆            ┆           ┆ omacy,    │
│           ┆      ┆ commiæer   ┆            ┆   ┆            ┆            ┆           ┆ Ecclesias │
│           ┆      ┆ Janoe…     ┆            ┆   ┆            ┆            ┆           ┆ tical…    │
│ …         ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 10261     ┆ 1261 ┆ DE L'AUBES ┆ [656, 657] ┆ … ┆ [1]        ┆ -1         ┆ null      ┆ ImperialP │
│           ┆      ┆ PINE.      ┆            ┆   ┆            ┆            ┆           ┆ rotestant │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆           ┆ Conflict, │
│           ┆      ┆ --- ## LE  ┆            ┆   ┆            ┆            ┆           ┆ Di…       │
│           ┆      ┆ ROY…       ┆            ┆   ┆            ┆            ┆           ┆           │
│ 10262     ┆ 1262 ┆ # A        ┆ [657, 658] ┆ … ┆ [0, 2, 3]  ┆ 2          ┆ PapalMedi ┆ PapalDipl │
│           ┆      ┆ MONSIEUR   ┆            ┆   ┆            ┆            ┆ ationTact ┆ omacy,    │
│           ┆      ┆ LE DAVHIN. ┆            ┆   ┆            ┆            ┆ ics,      ┆ HighPolit │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ Strateg…  ┆ icalC…    │
│           ┆      ┆ Le Ca…     ┆            ┆   ┆            ┆            ┆           ┆           │
│ 10263     ┆ 1263 ┆ LE         ┆ [658, 659] ┆ … ┆ [0]        ┆ 0          ┆ PapalDipl ┆ Diplomati │
│           ┆      ┆ CARDINAL   ┆            ┆   ┆            ┆            ┆ omaticEnd ┆ cNegotiat │
│           ┆      ┆ DE BOLOGNE ┆            ┆   ┆            ┆            ┆ orsement, ┆ ions,     │
│           ┆      ┆ ## AV R…   ┆            ┆   ┆            ┆            ┆ It…       ┆ PapalI…   │
│ 10264     ┆ 1264 ┆ AV ROT.    ┆ [659, 660] ┆ … ┆ [0]        ┆ 0          ┆ PapalDipl ┆ Diplomati │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ omaticEnd ┆ cNegotiat │
│           ┆      ┆ Du Mortier ┆            ┆   ┆            ┆            ┆ orsement, ┆ ions,     │
│           ┆      ┆ Ambaffadeu ┆            ┆   ┆            ┆            ┆ It…       ┆ PapalI…   │
│           ┆      ┆ …          ┆            ┆   ┆            ┆            ┆           ┆           │
│ 10265     ┆ 1265 ┆ ## A       ┆ [660, 661] ┆ … ┆ [0, 2, 12] ┆ 1          ┆ Ecclesias ┆ PapalDipl │
│           ┆      ┆ MONSIEUR   ┆            ┆   ┆            ┆            ┆ ticalProp ┆ omacy,    │
│           ┆      ┆ L'ADMIRAL  ┆            ┆   ┆            ┆            ┆ ertyDispu ┆ HighPolit │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ tes…      ┆ icalC…    │
│           ┆      ┆ Que c…     ┆            ┆   ┆            ┆            ┆           ┆           │
└───────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [2]:
clusters_w_subs = [0, 2, 12]

for i in clusters_w_subs:
    print("---" * 5)
    print(f"Cluster {i} tags:")
    clust_df = df.filter(pl.col("cluster") == i)
    print(clust_df["cluster_tags"].unique().to_list())
    print(clust_df["sub_cluster"].value_counts())
    for sub_c in clust_df["sub_cluster"].unique():
        print(f"\tSub-cluster {sub_c} tags:")
        print(
            clust_df.filter(pl.col("sub_cluster") == sub_c)["sub_labels"]
            .unique()
            .to_list()
        )

---------------
Cluster 0 tags:
['DiplomaticNegotiations, PapalImperialAlliances, AntiTurkishLeague, VenetianGeopolitics, DynasticTreatyFormation']
shape: (3, 2)
┌─────────────┬───────┐
│ sub_cluster ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 27    │
│ 2           ┆ 2     │
│ 1           ┆ 11    │
└─────────────┴───────┘
	Sub-cluster 0 tags:
['PapalDiplomaticEndorsement, ItalianCityStateAlliances, AntiImperialFlorentineRestoration, MercenaryTacticalOperations, FrancoPapalMilitaryCoordination']
	Sub-cluster 1 tags:
['PapalPeaceMediation, AntiImperialDiplomaticTactics, SecretNegotiationChannels, EcclesiasticalPoliticalLeverage, FrancoPapalDistrustDynamic']
	Sub-cluster 2 tags:
['EcclesiasticalAutonomyDebate, EpiscopalResidencyAdvocacy, AntiPatronageMoralism, HeresyModerationPolicy, ChurchReformFromBelow']
---------------
Cluster 2 tags:
['PapalDiplomacy, HighPoliticalCorrespondence, CardinalMinisters, FrancoImperialRivalry, EcclesiasticalStatecraft']
shape: (4, 2)
┌─────────────┬───────┐
│ sub_cluster ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 30    │
│ 3           ┆ 5     │
│ 2           ┆ 43    │
│ 1           ┆ 19    │
└─────────────┴───────┘
	Sub-cluster 0 tags:
['LorraineDynasticAlliances, PapalDiplomaticMediation, TerritorialNeutralityNegotiations, HighNobilityCorrespondence, SixteenthCenturyPowerBalancing']
	Sub-cluster 1 tags:
['EcclesiasticalPropertyDisputes, PapalJurisdictionalConflicts, EpiscopalRightsAssertion, LegalArbitrationBySecularAuthorities, ChurchStateTensionsInPiedmont']
	Sub-cluster 2 tags:
['PapalMediationTactics, StrategicNeutralityAnxiety, LegateLeveragePolitics, AntiImperialDistrust, EcclesiasticalArbitrationFocus']
	Sub-cluster 3 tags:
['NobleMilitaryServiceNegotiations, DiplomaticPowerBrokerage, TerritorialSovereigntyDisputes, ConditionalLoyaltyAgreements, StrategicMarriageAlliancesDiscourse']
---------------
Cluster 12 tags:
['DiplomaticCorrespondence, RoyalAllianceNegotiations, AmbassadorialDuties, InterCourtIntrigues, StateSecurityConcerns']
shape: (3, 2)
┌─────────────┬───────┐
│ sub_cluster ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 22    │
│ 1           ┆ 30    │
│ 2           ┆ 9     │
└─────────────┴───────┘
	Sub-cluster 0 tags:
['CardinalVirtueHagiography, EcclesiasticalDiplomaticNegotiation, TerritorialDisputeMediation, PapalImperialAllianceDynamics, ItalianBufferStatePolitics']
	Sub-cluster 1 tags:
['PapalMediationDiplomacy, HighStakesPeaceNegotiations, ImperialPapalPowerStruggles, StrategicItalianCityAlliances, ConfessionalNeutralityTensions']
	Sub-cluster 2 tags:
['DiplomaticTerritorialDisputes, PapalMediationEfforts, CardinalPoliticalCorrespondence, StrategicAllianceNegotiations, FrancoImperialPowerDynamics']

In [4]:
cluster = 12
subcluster = 0

cluster12_samples = (
    df.filter((pl.col("cluster") == cluster) & (pl.col("sub_cluster") == subcluster))
    .select(["markdown"])
    .sample(8)
    .to_series()
    .to_list()
)
parent_labels = (
    df.filter((pl.col("cluster") == cluster) & (pl.col("sub_cluster") == subcluster))
    .select(["cluster_tags"])
    .unique()
    .to_series()
    .to_list()
)
sub_labels = (
    df.filter((pl.col("cluster") == cluster) & (pl.col("sub_cluster") == subcluster))
    .select(["sub_labels"])
    .unique()
    .to_series()
    .to_list()
)
print(f" Cluster {cluster}, Sub-cluster {subcluster} samples:")
print(cluster12_samples)
print(" Parent labels:")
print(parent_labels)
print(" Sub-labels:")
print(sub_labels)

 Cluster 12, Sub-cluster 0 samples:

In [5]:
import polars as pl

df = pl.read_parquet(f"./books_work/ribier_v1/data/ribier_v1.parquet")
df.head()

shape: (5, 14)
┌───────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ letter_id ┆ id   ┆ markdown   ┆ pdf_pages  ┆ … ┆ soft_clust ┆ sub_cluste ┆ sub_label ┆ cluster_t │
│ ---       ┆ ---  ┆ ---        ┆ ---        ┆   ┆ er         ┆ r          ┆ s         ┆ ags       │
│ u32       ┆ u32  ┆ str        ┆ list[i64]  ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆      ┆            ┆            ┆   ┆ list[i64]  ┆ i64        ┆ list[str] ┆ list[str] │
╞═══════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 10000     ┆ 1000 ┆ LE PAPE    ┆ [46]       ┆ … ┆ [10]       ┆ -1         ┆ null      ┆ ["PapalCo │
│           ┆      ┆ PAVL III.  ┆            ┆   ┆            ┆            ┆           ┆ nciliarDi │
│           ┆      ┆ AV ROT     ┆            ┆   ┆            ┆            ┆           ┆ plomacy", │
│           ┆      ┆ FRANC…     ┆            ┆   ┆            ┆            ┆           ┆ "R…       │
│ 10001     ┆ 1001 ┆ LETTRE DE  ┆ [46, 47]   ┆ … ┆ [2, 9, 12] ┆ 3          ┆ ["PapalMe ┆ ["PapalDi │
│           ┆      ┆ MONLVC AV  ┆            ┆   ┆            ┆            ┆ diationAt ┆ plomacy", │
│           ┆      ┆ CARDINAL   ┆            ┆   ┆            ┆            ┆ tempts",  ┆ "Neutrali │
│           ┆      ┆ D…         ┆            ┆   ┆            ┆            ┆ "Su…      ┆ ty…       │
│ 10002     ┆ 1002 ┆ LETTRE DES ┆ [47, 48]   ┆ … ┆ [2, 9, 12] ┆ 0          ┆ ["Diploma ┆ ["Diploma │
│           ┆      ┆ AVOTERS ET ┆            ┆   ┆            ┆            ┆ ticNegoti ┆ ticEspion │
│           ┆      ┆ CONSEILL…  ┆            ┆   ┆            ┆            ┆ ations",  ┆ age",     │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆ "Su…      ┆ "Renai…   │
│ 10003     ┆ 1003 ┆ REMARQUES  ┆ [48, 49, … ┆ … ┆ [8]        ┆ -1         ┆ null      ┆ ["Diploma │
│           ┆      ┆ SVR LADITE ┆ 54]        ┆   ┆            ┆            ┆           ┆ ticNegoti │
│           ┆      ┆ VILLE DE … ┆            ┆   ┆            ┆            ┆           ┆ ations",  │
│           ┆      ┆            ┆            ┆   ┆            ┆            ┆           ┆ "Co…      │
│ 10003     ┆ 1003 ┆ Cethol.    ┆ [48, 49, … ┆ … ┆ [10, 13]   ┆ -1         ┆ null      ┆ ["PapalCo │
│           ┆      ┆ 1192. 6    ┆ 54]        ┆   ┆            ┆            ┆           ┆ nciliarDi │
│           ┆      ┆ commiæer   ┆            ┆   ┆            ┆            ┆           ┆ plomacy", │
│           ┆      ┆ Janoe…     ┆            ┆   ┆            ┆            ┆           ┆ "R…       │
└───────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [1]:
import polars as pl

# df = pl.read_parquet(f"./books_work/ribier_v1/data/ribier_v1.parquet")

In [4]:
clusters_w_subs = [0, 2, 12]
from clustering.clustering import (
    analyze_geometric_footprint,
    recommend_subclustering,
    recommend_k,
    recommend_k_refined,
)

for i in clusters_w_subs:
    print("---" * 5)
    print(f"Cluster {i} recommendation:")
    clust_df = df.filter(pl.col("cluster") == i)
    vectors = clust_df["embedding"]
    analyze_geometric_footprint(vectors, cluster_label=f"Cluster {i}")
    recommend_k(vectors, cluster_label=f"Cluster {i}")
    k = recommend_k_refined(vectors, cluster_label=f"Cluster {i}")
    print(f"Recommended k for Cluster {i}: {k}")

---------------
Cluster 0 recommendation:

Geometric Analysis: Cluster 0
  Total Samples: 40
  Dimensions to explain 80% variance: 21
  Anisotropy (Axis 1 / Axis 2): 1.02
  >>> Recommendation: SUB-CLUSTER (Occupies broad conceptual territory)

Sub-clustering Logic for Cluster 0:
  Total Dimensions available: 40
  Significant Axes (> average): 15
  Axes to reach 50% variance: 10
  >>> RECOMMENDED k: 6
Recommended k for Cluster 0: 2
---------------
Cluster 2 recommendation:

Geometric Analysis: Cluster 2
  Total Samples: 97
  Dimensions to explain 80% variance: 37
  Anisotropy (Axis 1 / Axis 2): 1.08
  >>> Recommendation: SUB-CLUSTER (Occupies broad conceptual territory)

Sub-clustering Logic for Cluster 2:
  Total Dimensions available: 97
  Significant Axes (> average): 31
  Axes to reach 50% variance: 15
  >>> RECOMMENDED k: 6
Recommended k for Cluster 2: 2
---------------
Cluster 12 recommendation:

Geometric Analysis: Cluster 12
  Total Samples: 61
  Dimensions to explain 80% variance: 28
  Anisotropy (Axis 1 / Axis 2): 1.27
  >>> Recommendation: SUB-CLUSTER (Occupies broad conceptual territory)

Sub-clustering Logic for Cluster 12:
  Total Dimensions available: 61
  Significant Axes (> average): 21
  Axes to reach 50% variance: 12
  >>> RECOMMENDED k: 6
Recommended k for Cluster 12: 2

In [3]:
all_vectors = df["embedding"]
analyze_geometric_footprint(all_vectors, cluster_label="All data")
recommend_k(all_vectors, cluster_label="All data")
recommend_k_refined(all_vectors, cluster_label="All data")

Geometric Analysis: All data
  Total Samples: 338
  Dimensions to explain 80% variance: 61
  Anisotropy (Axis 1 / Axis 2): 1.05
  >>> Recommendation: SUB-CLUSTER (Occupies broad conceptual territory)

Sub-clustering Logic for All data:
  Total Dimensions available: 338
  Significant Axes (> average): 81
  Axes to reach 50% variance: 22
  >>> RECOMMENDED k: 6

2

In [2]:
clusters_w_subs = [0, 2, 12]

for i in clusters_w_subs:
    print("---" * 5)
    print(f"Cluster {i} tags:")
    clust_df = df.filter(pl.col("cluster") == i)
    print(clust_df["cluster_tags"].unique().to_list())
    print(clust_df["sub_cluster"].value_counts())
    for sub_c in clust_df["sub_cluster"].unique():
        print(f"\tSub-cluster {sub_c} tags:")
        print(
            clust_df.filter(pl.col("sub_cluster") == sub_c)["sub_labels"]
            .unique()
            .to_list()
        )

---------------
Cluster 0 tags:
['DiplomaticAlliancesAndTreaties, PapalImperialVenetianRelations, OttomanConflictAndMediation, DynasticSuccessionAndProtection, MilitaryStrategyAndEspionage']
shape: (3, 2)
┌─────────────┬───────┐
│ sub_cluster ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 27    │
│ 1           ┆ 11    │
│ 2           ┆ 2     │
└─────────────┴───────┘
	Sub-cluster 0 tags:
['FrenchPapalDiplomaticIntermediaries, FlorenceTuscanyFrontier, CovertRegimeChange, MediciSuccessionVulnerability, CardinalAgentNetworks']
	Sub-cluster 1 tags:
['PapalLegationManipulation, ItalianPeninsulaFrontier, SubversiveMediation, PapalNeutralityErosion, LegateDoubleAgency']
	Sub-cluster 2 tags:
['CardinalCarpentrasResistance, RomanCurialPensions, EpiscopalAutonomyAssertion, TheologicalNonViolentReformation, EcclesiasticalPatronageRejection']
---------------
Cluster 2 tags:
['PapalDiplomaticNegotiations, ItalianGeopoliticalAlliances, CardinalMinisterCorrespondence, SixteenthCenturyNeutrality, DynasticMarriagePolitics']
shape: (4, 2)
┌─────────────┬───────┐
│ sub_cluster ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 2           ┆ 43    │
│ 0           ┆ 30    │
│ 1           ┆ 19    │
│ 3           ┆ 5     │
└─────────────┴───────┘
	Sub-cluster 0 tags:
['LorraineGuiseDynasty, LorraineDuchyFrontier, NeutralityEnforcement, DynasticSurvivalAnxiety, BorderStateDiplomacy']
	Sub-cluster 1 tags:
['SavoyardEcclesiasticalJurisdiction, TurinDiocese, SpoliumDispute, EpiscopalAuthorityAssertion, FeudalLegalContestation']
	Sub-cluster 2 tags:
['CardinalCarpi, PapalLegationNetwork, SubversionOfNonces, PapalNeutralityDistrust, LegateEspionageRivalry']
	Sub-cluster 3 tags:
['MontmorencyFrontierEnforcement, PicardyArtoisBorderlands, FugitiveExtraditionDemand, DynasticTerritorialDispute, CondottierePatronageNegotiation']
---------------
Cluster 12 tags:
['DiplomaticCorrespondence, RoyalAllianceNegotiations, AmbassadorialDuties, InterCourtIntrigues, TreatyComplianceDisputes']
shape: (3, 2)
┌─────────────┬───────┐
│ sub_cluster ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 0           ┆ 22    │
│ 1           ┆ 30    │
│ 2           ┆ 9     │
└─────────────┴───────┘
	Sub-cluster 0 tags:
['CardinalSadoletHagiography, PapalStatesCarpentras, VirtueExemplification, EcclesiasticalLegitimacyAnxiety, HagiographicPanegyricism}, {']
	Sub-cluster 1 tags:
['DanishRoyalIntermediary, BalticNorthSeaJunction, AllianceSolidification, NeutralityPreservationAnxiety, PeerToPeerDiplomacy']
	Sub-cluster 2 tags:
['MontmorencyExtraditionDispute, SaintPolComtéFrontier, FugitiveRepatriationDemand, SovereigntyTerritorialAnxiety, MilitaryCommanderDiplomacy']

In [14]:
cluster = 2
subcluster = 3

cluster12_samples = (
    df.filter((pl.col("cluster") == cluster) & (pl.col("sub_cluster") == subcluster))
    .select(["markdown"])
    .sample(5)
    .to_series()
    .to_list()
)
parent_labels = (
    df.filter((pl.col("cluster") == cluster) & (pl.col("sub_cluster") == subcluster))
    .select(["cluster_tags"])
    .unique()
    .to_series()
    .to_list()
)
sub_labels = (
    df.filter((pl.col("cluster") == cluster) & (pl.col("sub_cluster") == subcluster))
    .select(["sub_labels"])
    .unique()
    .to_series()
    .to_list()
)
print(f" Cluster {cluster}, Sub-cluster {subcluster} samples:")
print(cluster12_samples)
print(" Parent labels:")
print(parent_labels)
print(" Sub-labels:")
print(sub_labels)

 Cluster 2, Sub-cluster 3 samples:

In [13]:
sadolet = df.filter(pl.col("markdown").str.contains("sadol", literal=True))
sadolet

shape: (0, 14)
┌───────────┬─────┬──────────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ letter_id ┆ id  ┆ markdown ┆ pdf_pages ┆ … ┆ soft_cluste ┆ sub_cluster ┆ sub_labels ┆ cluster_ta │
│ ---       ┆ --- ┆ ---      ┆ ---       ┆   ┆ r           ┆ ---         ┆ ---        ┆ gs         │
│ u32       ┆ u32 ┆ str      ┆ list[i64] ┆   ┆ ---         ┆ i64         ┆ str        ┆ ---        │
│           ┆     ┆          ┆           ┆   ┆ list[i64]   ┆             ┆            ┆ str        │
╞═══════════╪═════╪══════════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
└───────────┴─────┴──────────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
cluster9_sampels = (
    df.filter(pl.col("cluster1") == 9)
    .select("markdown")
    .sample(5)
    .to_series()
    .to_list()
)
cluster9_sampels

ColumnNotFoundError: unable to find column "cluster1"; valid columns: ["letter_id", "id", "markdown", "pdf_pages", "title", "chunk_id", "word_length", "full_markdown", "embedding", "cluster", "soft_cluster", "sub_cluster", "sub_labels", "cluster_tags"]

In [9]:
cluster12_samples = (
    df.filter(pl.col("cluster1") == 12)
    .select("markdown")
    .sample(5)
    .to_series()
    .to_list()
)
cluster12_samples

["\n\nD I L E C T E fili, salutem &amp; Apostolica m benedictionem. Audito Christianiflimi Regis sapienti judicio, quo nobilitatem tuam ad supremum Regni Francie Magistratum evexit, magna profecto latitia affecti sumus. Quot viro &amp; probo, &amp; prudenti, &amp; Q. iij\n\nOriginal du 11. Mars.3\n\nLe ferey voir cyapres, par divers les Lettres, que les Papes traitent les Ducs même fou. Certains de Nobiliu vis &amp; de Nobilius.\n\nLes Eloges du Pape &amp; du Connoissable se veront cyapres.\n\nOriginal.\n\n\n\n# LETTRES ET MEMOIRES DESTAT.\n\nmultis virtutibus ornato, ex potestas accellerit, quâ &amp; rei Christianae, &amp; Apostolicae Sedis possit maiori multo auctoritate patrocinari. Qualem mentem, animum qu in omnibus actionibus suis temper ostendit. Graculamur itaq; primum Regia Majestati, quæ beneficiu dando accepit, cum digno dedit. Deinde Nobilitati tuæ, quæ tantum Principis iudicium in se promeruit. Er speramus hoc, Deo benevolente atq; auctore, factum esse, vit ea Fidelium rem atque expeditionem à nobis aduerfum Turcas fusceptam maiore suffragio valeat adiuare. Ad cuius auxilium, aut potius stabilimentum, vt Majestatem praetam, licet optime, vt credimus animatam, suis hortutibus impellere velit rogamus. Certem enim si Christianissimi Principis debitum, si veterum monumenta, &amp; maiorum gesta renoluiimus, Coronæ Francorum propria est, &amp; fuit temper, expeditiocontra Infideles. Datum Romæ apud sanctum Petrum sub annulo Pificatoris, die 12. Martij. M. D. XXXVIII. Pontificatus nostri anno quarto. FABIVS VIGIL.\n\nEt au dessus, Dilecto Filio nobili Viro Domino de Montmorandi Regni Franciæ Connoissabili.\n\n\n\n# L'ARCHEUESQUE DE BORDEAVS AV CONNESTABLE.\n\nDe quelques Lutheriens qui s'effoient retirés de Bordeaux en Languedoc, Gouvernement dudit Connoissable.\n\nMonsiègnèvr, il est depuis demy an en ça venu vn Prefcheur en cette Ville, qui a été logé en l'Abbaye sainte Croix, qui est lieu écarté comme sauvé, &amp; loing de celuy où les gens de sauroit habitent, lequel sous ombre de ses prédications &amp; lectures a secrètement par les maisons &amp; copagnies privées semé beaucoup d'erreurs &amp; propositions damnées devant que l'on s'en soit apperceu, tellement que plusieurs jeunes Épôliers &amp; gens de bas est ont été signalés par l'ay, qu'ils adheroient totalement à l'opinion des Lutheriens lequel Prefcheur est ant aduerty que Messieurs de la Cour de Parlement &amp; mes Officiers estoient après pour le constituer prisonnier, s'est sauvé de nuit, &amp; à ce que j'entends retiré en voître gouvernement de Languedoc.\n\nMonseigneur, incontinent après avoir été aduerty de ce que dessus, &amp; que j'ay estimé cette frontière hors de danger &amp; surprise, par la présence du Roy de Navarre, aucuns de ladite Cour de Parlement &amp; moy sommes continuellement après à faire procès à ceux que trouvons entre chargés, &amp; espérons éteindre pour cette fois l'impression &amp; erreurs dudit Prefcheur, &amp; pour l'advenir serait grandement requis avoir vue Bulle du Pape semblable à celle que le feu Pape Clement fit dépêcher à Marseille, pour préférer en terme à ceux qui pourroient être dévoyés de la foi &amp; constitutions de l'Église, pour abjurer &amp; revenir à nous, car autrement est à craindre que les susdits &amp; autres tôbent en semblables erreurs, je suis assuré que qui n'aura ladite Bulle, ils seront à toute heureLIVRE II. ANNÉE M. D. XXXVIII. 87\n\nadmis, faisons semblant de se repentir &amp; abjurants : à quoy je vous supplie très-humblement, Monseigneur, tenir main, &amp; encore que ladite Cour de Parlement ayt bien fait son devoir jusqu'à présent, faire que le Roy leur écrire de me faire en cet endroit toute la faveur &amp; ayde qu'il leur sera possible, &amp; sans épargner aucun de quelque effet ou condition qu'il puisse être, &amp; à moy semblablement ; car lesdites Lettres profiteront beaucoup pour tenir les gens en crainte.\n\nMonseigneur, Moniteur de Tarbes mon Neveu m'a écrit, que vous luy aués dit que vous me feriés acquitter par le Roy le don gratuit équipolant à trois décimes, dont très-humblement vous remercie, vous admis, Monseigneur, que ne s'gauriés ce faire à personne, qui plus vous voulaît faire service, ne qui ayt meilleur besoin d'être aydé &amp; secouru que moy, veu les grands frais &amp; mises qu'il m'a convenu &amp; convient faire journellement pour le service dudit Seigneur.\n\nMonseigneur, je prie le Créateur qu'il vous doint en santé très-longue vie. A Bordeaux ce 12. jour de Mars.\n\nVous fériés beaucoup pour le service de Dieu &amp; du Roy, si c'estoit votre plaisir écrire à Môseur le Senechal de Toulouse votre Lieutenant, qu'il s'est costituit prisôniers ceux qui se sont retirés audit Toulouse &amp; ailleurs en votre Gouvernement, contre lesquels les informations, ou captatur des Commissaires de la Cour &amp; de moy luy sont envoyés.\n\nVotre très-humble &amp; très-obéissant serviteur\n\nC. DE GRAMONT Arch. de Bordeaux;\n\nEt au dessus, A Monseigneur, Monseigneur le Connestable.",
 "\n\nCe Sieur de Granuelle, avec lequel l'Ambassadeur auoit tant de communications &amp; de confiance, s'appelloit Nicolas Perenot, surnommé de Granuelle, à cause d'une terre Seigneuriale de ce nom, qu'il auoit acquise. Il estoit lors de cette dernière Lettre, Chancelier &amp; premier Secrétaire de l'Empereur, &amp; en plus grand crédit, authorisé &amp; confidence auprès de luy, que nul autre ; ayant en cela succédé au Cardinal Mercurain Gattinare, qui durant sa vie estoit le Confidentissime. Ce fut par son excellent esprit, que Granuelle s'éteva ainsi : car il estoit de basse naissance, &amp; selon quelques Historiens, fils d'un Maréchal de forge, ou Servierier dans Bezançon, au Comté de Bourgogne. Son Père le voyant d'esprit qui promestoit beaucoup, prit soin de luy faire apprendre à bien lire &amp; écrire ; puis le mit Clerc chez un Procureur, où il se rendit si bon Praticien, que le Chancelier de Bourgogne l'ayant pris en estime, le donna pour Secrétaire à Madame Marguerite d'Autriche, Duchesse douairière de Savoye, Tante de l'Empereur, lequel depuis le désira pour l'y-même, &amp; en fit après quelque temps de service\n\nStrada, Aubery &amp; autres.LIVRE III. ANNÉE M. D. XXXIX. 371\n\nnon seulement son premier Secrétaire d’un Chanceller, mais son première principal Ministre d’Etat. Aussi étroit-il sort efflairé, prudent et judicieux, même très-modéré pacifique en ses conseils et négociations, concernant les troubles des nouvelles Sectes d’Allemagne, car un de ces nouveaux religionnaires des plus effimes, parmi eux rapportés, que Granuelle défait tellement la Paix et la tranquillité entre les Catholiques et les protestants, que ce fut lui qui s’éteint, disposait d’Empereur en 1340 à la vouloir bien aussi. Il mourut en 1350 après avoir eu, dit le même Historien, la connaissance presque lui seul des sécrecs du profond du cœur de son Prince l’espace de vingt ans. Mais ce qui est encore plus merveilleux, c’est d’avoir laissé sa direction des affaires d’Etat aussi l’affection, créance et confiance entière, qu’avait l’Empereur en lui, à Antoine de Granuelle son fils, comme si elles eussent été héréditaires. Il avait par prévoyance et penetration de l’avenir, si bien élevé, instruit et exercé sous lui ce fils, qu’il s’était rendu capable du Ministère d’infinue aux bonnes grâces de l’Empereur, qui le prit depuis en telle estime, qu’en rejoignant ses États à Philippe II. Son fils, il lui conseilla de faire Antoine de Granule, lors Ensigne d’Arras, son premier Ministre : conseil que le Roy Philippe faisait ponctuellement, qu’il pourra ensuite la pourpre et dignité de Cardinal.\n\nM. de Thun, I.6 le qualité versus magnapandentia.\nSindon list. 12 vers la fin.",
 "\nL'éloge du Sieur Card. se verra cyapera, duquel cy. deuant p. 171. &amp; 1. Origin.\n\nLettre de remerciement &amp; compliment du Cardinal Farnese, il est fait petit fils du Pape Paul III.\n\nMONSEIGNOR, oltre l'obligazioni ch'io ho, &amp; debbo hauere à V. Excellentia, per li continui meriti, &amp; bone opere sue verso N. S. questa sancta Sede &amp; tutta Christianita, me fa aggiunge anche nouamenté questa particolare della cura che si è degnata pigliare della mia spedizione d'Altacomba, hauendo promesso à Mons. d'Yurea di farla fare come la Corte giunge a Parigi, Di che certo ho pigliato infinito piacere, non tanto per l'interesse del negocio, delquale, per le manifeste ragioni mie, non ho mai sperato altro fine dalla bona iustizia di corretto Regno, Quanto per la stima che io faccio, che si conosca, che l'Excellentia V. tenga memoria di me, &amp; che la feruica, &amp; affettione singolare ch'io porto alla Majesta del Re, &amp; a lei sia hausta in qualche considerazione. Glie ne rendo dunque quelle gracie che io posso maggiori.\n\nC'estoit le Nonce du Pape en France.LIVRE II. ANNEE M. D. XXXVIII. 239\nDECEMBRE.\n\nmaggiori, &amp; la prego per l'effetto del negocio quartilo fara tempo, che per la causa fopradetta mi fara di molto fauote &amp; gratia; Nel refto fupplita Monsegnor d'Yurea, alquale mi rimetto. Raccomandandomi di continuo à V. Excellentia, &amp; pregandola à degnarfi di far le mie humilimi raccomandationi alla bona gratia di fua Majesta &amp; delii ferenissimi figli miei fignori, che Dio li conferui tutti in longa &amp; felice vita. Di Roma alli 3. di Decembre 1338. Plus bas, D. V. Excellentia fengitore il Card. FARNÆZ. Au dessus, Al III. &amp; Excell. Segnor Monsegnor il Consistabile di Francia.\n\n",
 "\n\nLe Maréchal de Montejan Lieutenant du Roy en Piémont l'ay donne aduis de la necessité des viures, &amp; de l'ordre qu'il tient pour régler les confins entre le Roy &amp; l'Empereur.\n\nMonseigneur, vous aues bien amplement entendu par le general de Bretagne l'esrar &amp; dispose de par deca, à quoy est requis &amp; necessaire de pournoir, messement au paiement des Lansqueners dont ie vous ay tant de fois écrit, &amp; pareillement à celuy des gens de pied François qui echet le premier jour d'Avril, lesquels j'ay tous reduits dedans les Villes où il ne leur est possible de pouuoir viure sans estre payés pour la grande cherte des viures qui y est &amp; la difficulté d'y en faire amener; c'est vne des choses dont nous avons plus de besoin pour cette heure : à cette cause ie vous supplie, Monseigneur, y vouloir donner ordre, &amp; en ce faisant vous pouués estre afeuré que vous ferés hors de peine du coste de deca, ie vous pensois enuoyer Monseigneur de Langey pour plus amplement vous en aduertir, mais j'ay receu Lettres de l'Eusque de Cazal par lesquelles il m'a mande comme il s'en vient accompagne des Sieurs de Senchir Brauo, Ican de Vergaye, le Vittarin, &amp; du Sieur Benere, en cette Ville de Montcallier pour vuider &amp; conclure tous les differents &amp; occurrences qui pourroient estre faits à la Treve, touchant les confins du Roy &amp; de l'Empereur, où la presence dudit Sieur de Langey est merucilleusement requise pour debattre les choses avec eux en ce qui touche l'interest &amp; service dudit Seigneur, afin que d'iey en auant il n'en puisse arriuer inconvenient, &amp; que chacun scache &amp; entende ce qu'il aura à faire : cependant le Sieur d'Assier present porteur s'en va en qui ie remets le surplus, vous suppliant, Monseigneur, le vouloir croire, &amp; me tenir toujours en voître bonne grace tres-humble &amp; recommandé, priant Dieu vous donner, Monseigneur, bonne &amp; longue vie. A Montcallier le vingt-sixième jour de Mars.\n\nDepuis ces Lettres écrites ie me suis aduisé de ne faire venir les Députés du Marquis de Gaast en cette Ville, pour plusieurs raisons, &amp;138 LETTRES ET MEMO IRES D'ESTAT;\n\nd'envoyer Monfleur de Languy parler à eux à Paris, afin qu'ils ne connoissent rien de nos viures ni de nos fortifications lesquelles je vous assure encore un coupÊtre telles qu'il ne nous fera point de mal, moyennant qu'il vous plâse nous envoyer des vitres. Voître très-humble &amp; très-obéissant serviteur MONTIJAN.\n\nMonfeigneur, vous fœtiez comme le Seigneur Jean-Paule a-t-oujours été par déça, &amp; me semble que feriés merutelleusement bien de luy faire écrire une bonne Lettre du contentement qu'a le Roy du feruice qu'il fait : aussi Monfeigneur, je ne veux oublier à vous ramenteuoir qu'il vous plâse m'accorder le Committé des guetres, dont je vous ay cy-deuant écrit, &amp; de plus en plus m'obligéte à vous faire feruice ; car cela me fera un grand foulagement pour la fiance que j'ay en luy.\n\nEt au dessus, A Monfeigneur, Monfeigneur le Conneitable.\n\nRemarques touchant ledit Sieur Montejan.\n\nLe choix des Committéistes de guerre ne dépend pas des Lieutenants de Roy en ses Armées &amp; Proustes\n\nEn Son Recueil des Maréchaux de France.\n\nLire 8. de ses Mémoires.\n\nLe Sieur Godefroy le nomme &amp; qualifie R en Sieur de Montejan au pays d'Anjou, Baron de Sille &amp; de Beaupreau, Gouverneur &amp; Lieutenant général du Roy en Piémont, &amp; aquoite qu'il recevra le Baron de Maréchal de France en 1330. en quoi il y a une erreur notable, laquelle j'astrebur p'utost à l'imprimeur qu'à l'Auteur même dudit Recueil, qui a été très-oxaÃ§ &amp; judicieux en tous ses Ecrits : il est certain que ledit Seigneur de Montejan ne fut Maréchal de France qu'en 1337. comme on composa lors, parce que l'année ne satisfait qu'à Pafques ou en 1338. selon notre compte préféré : j'ay pour macaution entre-autres Historiens le Seigneur de Languy, G. du Bellay qui dit affirmativement qu'après la Trêve d'Italie faite entre le Roy &amp; l'Empereur &amp; publiée en Novembre 1337. le Roy qui avait passé les Monts voulant recuser en France pourueur auparavant par sa prudence aux affaires du Piémont, &amp; y établit le Seigneur de Montejan Gouverneur &amp; Son Lieutenant Général, puis sa Majesté étant de retour en Son Royaume &amp; voulant reconnaître dignement ceux qui l'avaient bien servu dans les guerres précédentes, honora le grand Maître de Montmorency de l'Office de Conneitable en 1338. &amp; donna le sien de Maréchal de France au dit Sieur de Montejan ; cet Autre urêt d'autant plus croyable parce qu'il servait le Roy sous Montejan dans le Piémont en qualité de Gouverneur particulier de Turin, &amp; même ils eurent quelque différent, comme on verra cy-après, pour l'exercice &amp; autorité de leurs charges. Ledit Seigneur de Montejan passé dans toutes nos Histoires pour un bard &amp; très-bazardieux Chevalier, il fut du nombre des préveniers de marque dans la malheureuse &amp; funeste journée de Paris, &amp; depuis encore en la guerre de Provence en 1338. Tuy &amp; Boisy tous deux Chevaliers de l'Ordre &amp; commandants chacun une Compagnie de cinquante hommes d'armes furent pris par les ennemis pour l'être trop auanturés &amp; avancés sur le dessein qu'ils avaient des surprendre Dom Ferrand de Gonzague qui menait l'avantgarde de l'Empereur. Cette disgrace de Montejan chef de l'entreprise ne l'éloigna point des bonnes graves du Roy &amp; de l'efdime qu'il faisait de son courage, mais sa Majesté n'en fut pas longuement servie depuis qu'il fut son LieutenantLIVRE II. ANNE'E M. D. XXXVIII. 139\n\nen Piémont et Maréchal de France; car il mourut selon nos Historiens dès l'année 1138. Et selon la pure vérité en l'année suivante seulement, comme le vérifira clairement par une Lettre originale que j'ay de sa main du mois de May 1139, qui sera mise en son ordre.\n\nIl portait d'oe fetté de goreau.\n\n",
 "\n\nLe Seigneur de la Cra on des Confidens du Duc de Sauoye, représente la sincere affection qu'a son Duc envers le Roy; que sa MaieSté a interreff de confermer &amp; maintenir cette maison; que Nice est ville de conséquence, que le St. Suaire y est, &amp; les principaux titres, joyaux &amp; meubles de Sauoye.\n\n### Origin.\n\nMONSEIGNEVR, depuis mes dernières lettres, Monfieur de Sauoye s'est trouvé trois ou quatre iours mal à son aife, chose qui luy aduient fouuent depuis quelque temps en ça. Surquoy me trouvant auec l'homme affectionné que vous connoissés, il m'a commencé des propos des inconueniens qui poutoient aduenit, si noître Seigneur prenait à foy mondit Sieur de Sauoye, &amp; des dangers où pouroit tomber Monfieur le Prince son fils estant en si bas âge, veu que tous ceux qui sont aupres de luy, sont à la deuotion de l'Empereur. Pareillement en quelles mains pouroit venir cette maison qui est de la conséquence que vous fçavez; ensemble les meubles qui y sont dedans, à fçauoir le St. Suaire, la plus-part des principaux titres de la maison de Sauoye, qui peuvent grandement feruir au Roy &amp; ses successeurs, &amp; plusieurs autres choses, comme tapisseries &amp; pierreries, qui ne sont de petite importance estans sous la chatge du susdit, dont aduenant tel cas de mort, mondit Sieur le Prince, le peu de reste qu'il a de son estat, ensembleLIVRE III. ANNE'E M. D. XXXIX. 409\n\ncette maifon &amp; le tout que dessus, féroit en grand danger de tomber en totale tuine : tellement qu'il y auroit bien peu d'effperance d'y pouvoir remedier pour l'advenir ; veu metmement le mauvais confeil qui est ivv, la mauvaise volonré des voifins, qui font les Geneuois qui ne t'aflent iournelement que de surprendre cette maifon. A l'occasion de quoy ledit perlonnage m'a prié de vous vouloir eferire &amp; aduertir des chofes fufdites, à ce qu'il vous plaife y aduifer : comme s'il vouloit dire par refolution, qu'il pleiât au Roy d'vfer enuers mondit Sieur de Sauoye, de sa liberalité accouftumée, &amp; de venir à quelque party raisonnable : de forte que mondit Sieur de Sauoye, &amp; ses sujets foyent gaignez perpetuellement pour le feruice du Roy &amp; ses successeurs ; me faifant entendre que tout cela se peut aifement reduire par voître moyen. Je vous puis bien affeurer, Monfeigneur, que ledit homme n'en parle que pour l'affection &amp; bonne volonté qu'il a d'estre perpetuel feruiteur du Roy, &amp; sur tous les propos qu'il m'a tenu en cet endroit, je ne puis confiderer ny connoisse qu'ils viennent d'autre lieu, que de la part de mondit Sieur de Sauoye son Maifre.\n\nMonfeigneur, ledit homme m'a dit en outre que depuis trois jours, il luy a efté faite quelque ouverture, d'où procede la pratique de Cefar Duc ; &amp; dedans peu de jours, il m'en fera entendre la verité pour le vous faire feauoir, afin que vous ayés pleine connoissance, que mondit Sieur de Sauoye ny eft en rien compris, mais eft vne chofe controuvée, pour donner ennuy à beaucoup de gens sans occasion, &amp; aujourd'hui mefmes mondit Sieur de Sauoye m'en a tenu propos, qui fait ainsi qu'il dit, tout ce qui luy eft possible pour en feauoir la verité, &amp; vous en aduertir. De Nice ce 16. Mars 1539. Voître tres-humble &amp; tres-obéissant feruiteur."]

In [7]:
from clustering.clustering import create_cluster
import polars as pl

folder = "ribier_v1"

df1 = pl.read_parquet(f"./books_work/{folder}/data/{folder}_chunked.parquet")
docs = df1["embedding"].to_list()
cluster3, soft3, samples3, iters3 = create_cluster(docs, run_num=1, soft_assign=False)
cluster4, soft4, samples4, iters4 = create_cluster(docs, run_num=2, soft_assign=False)
df1 = df1.with_columns(cluster3=pl.Series(cluster3), cluster4=pl.Series(cluster4))
print("Cluster 3:")
with pl.Config(tbl_rows=25):
    display(df1["cluster3"].value_counts().sort("cluster3"))
print("Cluster 4:")
with pl.Config(tbl_rows=25):
    display(df1["cluster4"].value_counts().sort("cluster4"))

  Estimated number of clusters: 14
  Restart 1/10 (seed 10) — score: 0.9402
  Restart 2/10 (seed 11) — score: 0.9400
  Restart 3/10 (seed 12) — score: 0.9403
  Restart 4/10 (seed 13) — score: 0.9403
  Restart 5/10 (seed 14) — score: 0.9398
  Restart 6/10 (seed 15) — score: 0.9402
  Restart 7/10 (seed 16) — score: 0.9404
  Restart 8/10 (seed 17) — score: 0.9399
  Restart 9/10 (seed 18) — score: 0.9401
  Restart 10/10 (seed 19) — score: 0.9393
  Best score: 0.9404
  Estimated number of clusters: 14
  Restart 1/10 (seed 20) — score: 0.9406
  Restart 2/10 (seed 21) — score: 0.9400
  Restart 3/10 (seed 22) — score: 0.9396
  Restart 4/10 (seed 23) — score: 0.9399
  Restart 5/10 (seed 24) — score: 0.9401
  Restart 6/10 (seed 25) — score: 0.9394
  Restart 7/10 (seed 26) — score: 0.9403
  Restart 8/10 (seed 27) — score: 0.9402
  Restart 9/10 (seed 28) — score: 0.9386
  Restart 10/10 (seed 29) — score: 0.9399
  Best score: 0.9406
Cluster 3:

shape: (14, 2)
┌──────────┬───────┐
│ cluster3 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 75    │
│ 1        ┆ 21    │
│ 2        ┆ 17    │
│ 3        ┆ 78    │
│ 4        ┆ 6     │
│ 5        ┆ 26    │
│ 6        ┆ 23    │
│ 7        ┆ 9     │
│ 8        ┆ 3     │
│ 9        ┆ 28    │
│ 10       ┆ 42    │
│ 11       ┆ 54    │
│ 12       ┆ 24    │
│ 13       ┆ 7     │
└──────────┴───────┘

Cluster 4:

shape: (14, 2)
┌──────────┬───────┐
│ cluster4 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 28    │
│ 1        ┆ 65    │
│ 2        ┆ 19    │
│ 3        ┆ 9     │
│ 4        ┆ 23    │
│ 5        ┆ 6     │
│ 6        ┆ 37    │
│ 7        ┆ 68    │
│ 8        ┆ 11    │
│ 9        ┆ 78    │
│ 10       ┆ 8     │
│ 11       ┆ 14    │
│ 12       ┆ 25    │
│ 13       ┆ 22    │
└──────────┴───────┘

In [11]:
df.sample(5)

shape: (5, 12)
┌───────────┬───────┬─────────────┬────────────┬───┬────────────┬────────────┬──────────┬──────────┐
│ letter_id ┆ id    ┆ title       ┆ pdf_pages  ┆ … ┆ full_markd ┆ embedding  ┆ cluster1 ┆ cluster2 │
│ ---       ┆ ---   ┆ ---         ┆ ---        ┆   ┆ own        ┆ ---        ┆ ---      ┆ ---      │
│ u32       ┆ u32   ┆ str         ┆ list[i64]  ┆   ┆ ---        ┆ list[f64]  ┆ i64      ┆ i64      │
│           ┆       ┆             ┆            ┆   ┆ str        ┆            ┆          ┆          │
╞═══════════╪═══════╪═════════════╪════════════╪═══╪════════════╪════════════╪══════════╪══════════╡
│ 10129     ┆ 10129 ┆ APOLOGIE    ┆ [327, 328, ┆ … ┆            ┆ [-0.043457 ┆ 8        ┆ 11       │
│           ┆       ┆             ┆ … 356]     ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ des permis ┆ -0.029053, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ sions de   ┆ … -0.01…   ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ Duel obte… ┆            ┆          ┆          │
│ 10082     ┆ 10082 ┆ LA CHAMBRE  ┆ [226, 227] ┆ … ┆            ┆ [-0.014221 ┆ 12       ┆ 8        │
│           ┆       ┆ DES         ┆            ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆ COMPTES.    ┆            ┆   ┆ Elle       ┆ -0.008301, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ depute     ┆ … -0.02…   ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ tant vers  ┆            ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ le Roy…    ┆            ┆          ┆          │
│ 10050     ┆ 10050 ┆ AVDIT       ┆ [174]      ┆ … ┆            ┆ [-0.025146 ┆ 4        ┆ 0        │
│           ┆       ┆ CONNESTABLE ┆            ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ J. Jacques ┆ -0.019775, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ Castron    ┆ … 0.001…   ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ Commis à … ┆            ┆          ┆          │
│ 10022     ┆ 10022 ┆ AVTRES      ┆ [82, 83, … ┆ … ┆            ┆ [-0.032715 ┆ 4        ┆ 11       │
│           ┆       ┆ ARTICLES    ┆ 85]        ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆ DÉBATTVS    ┆            ┆   ┆ en ladite  ┆ 0.003464,  ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ communicat ┆ … 0.0058…  ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆ ion non …  ┆            ┆          ┆          │
│ 10271     ┆ 10271 ┆ CAROLVS.    ┆ [568]      ┆ … ┆            ┆ [-0.048584 ┆ 1        ┆ 2        │
│           ┆       ┆             ┆            ┆   ┆            ┆ ,          ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆            ┆ -0.026123, ┆          ┆          │
│           ┆       ┆             ┆            ┆   ┆            ┆ … -0.03…   ┆          ┆          │
└───────────┴───────┴─────────────┴────────────┴───┴────────────┴────────────┴──────────┴──────────┘

shape: (5, 13)
┌───────────┬───────┬─────────────┬────────────┬───┬────────────┬──────────┬──────────┬────────────┐
│ letter_id ┆ id    ┆ title       ┆ pdf_pages  ┆ … ┆ embedding  ┆ cluster1 ┆ cluster2 ┆ subcluster │
│ ---       ┆ ---   ┆ ---         ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ 1          │
│ u32       ┆ u32   ┆ str         ┆ list[i64]  ┆   ┆ list[f64]  ┆ i64      ┆ i64      ┆ ---        │
│           ┆       ┆             ┆            ┆   ┆            ┆          ┆          ┆ null       │
╞═══════════╪═══════╪═════════════╪════════════╪═══╪════════════╪══════════╪══════════╪════════════╡
│ 10262     ┆ 10262 ┆ AV CARDINAL ┆ [554]      ┆ … ┆ [-0.047852 ┆ 12       ┆ 8        ┆ null       │
│           ┆       ┆ DV BELLAY.  ┆            ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ -0.026733, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … 0.021…   ┆          ┆          ┆            │
│ 10292     ┆ 10292 ┆ GOSTAVVS.   ┆ [592, 593, ┆ … ┆ [-0.044434 ┆ 13       ┆ 8        ┆ null       │
│           ┆       ┆             ┆ … 595]     ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ -0.009094, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … -0.02…   ┆          ┆          ┆            │
│ 10009     ┆ 10009 ┆ PAVLVS PAPA ┆ [46]       ┆ … ┆ [0.00531,  ┆ 11       ┆ 6        ┆ null       │
│           ┆       ┆ III.        ┆            ┆   ┆ 0.01001, … ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ -0.019653… ┆          ┆          ┆            │
│ 10029     ┆ 10029 ┆ REMARQUES   ┆ [116, 117, ┆ … ┆ [-0.001022 ┆ 9        ┆ 7        ┆ null       │
│           ┆       ┆ SVR LEDIT   ┆ … 120]     ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆ SIEVR       ┆            ┆   ┆ -0.030273, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … 0.020…   ┆          ┆          ┆            │
│ 10006     ┆ 10006 ┆ ENSVIT      ┆ [27, 28, … ┆ … ┆ [-0.039062 ┆ 12       ┆ 11       ┆ null       │
│           ┆       ┆ LEDIT       ┆ 39]        ┆   ┆ ,          ┆          ┆          ┆            │
│           ┆       ┆ PLAIDOYE.   ┆            ┆   ┆ -0.052002, ┆          ┆          ┆            │
│           ┆       ┆             ┆            ┆   ┆ … -0.03…   ┆          ┆          ┆            │
└───────────┴───────┴─────────────┴────────────┴───┴────────────┴──────────┴──────────┴────────────┘