In [8]:
from venv import create

from clustering.clustering import create_cluster
import polars as pl

folder = "ribier_v1"
df = pl.read_parquet(f"./books_work/{folder}/data/{folder}_chunked.parquet")
docs = df["embedding"].to_list()
cluster, soft, samples, iters = create_cluster(docs, run_num=1)
cluster1, soft1, samples1, iters1 = create_cluster(docs, run_num=2)
df = df.with_columns(cluster1=pl.Series(cluster), cluster2=pl.Series(cluster1))
print("Cluster 1:")
with pl.Config(tbl_rows=25):
    display(df["cluster1"].value_counts().sort("cluster1"))
print("Cluster 2:")
with pl.Config(tbl_rows=25):
    display(df["cluster2"].value_counts().sort("cluster2"))

  Estimated number of clusters: 14
  Restart 1/10 (seed 10) — score: 0.9361
  Restart 2/10 (seed 11) — score: 0.9361
  Restart 3/10 (seed 12) — score: 0.9353
  Restart 4/10 (seed 13) — score: 0.9361
  Restart 5/10 (seed 14) — score: 0.9366
  Restart 6/10 (seed 15) — score: 0.9372
  Restart 7/10 (seed 16) — score: 0.9372
  Restart 8/10 (seed 17) — score: 0.9361
  Restart 9/10 (seed 18) — score: 0.9371
  Restart 10/10 (seed 19) — score: 0.9365
  Best score: 0.9372
  Estimated number of clusters: 14
  Restart 1/10 (seed 20) — score: 0.9360
  Restart 2/10 (seed 21) — score: 0.9365
  Restart 3/10 (seed 22) — score: 0.9363
  Restart 4/10 (seed 23) — score: 0.9368
  Restart 5/10 (seed 24) — score: 0.9371
  Restart 6/10 (seed 25) — score: 0.9363
  Restart 7/10 (seed 26) — score: 0.9363
  Restart 8/10 (seed 27) — score: 0.9366
  Restart 9/10 (seed 28) — score: 0.9345
  Restart 10/10 (seed 29) — score: 0.9359
  Best score: 0.9371
Cluster 1:

shape: (14, 2)
┌──────────┬───────┐
│ cluster1 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 21    │
│ 1        ┆ 19    │
│ 2        ┆ 4     │
│ 3        ┆ 4     │
│ 4        ┆ 19    │
│ 5        ┆ 22    │
│ 6        ┆ 11    │
│ 7        ┆ 5     │
│ 8        ┆ 18    │
│ 9        ┆ 76    │
│ 10       ┆ 9     │
│ 11       ┆ 24    │
│ 12       ┆ 121   │
│ 13       ┆ 60    │
└──────────┴───────┘

Cluster 2:

shape: (14, 2)
┌──────────┬───────┐
│ cluster2 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 23    │
│ 1        ┆ 33    │
│ 2        ┆ 18    │
│ 3        ┆ 10    │
│ 4        ┆ 11    │
│ 5        ┆ 10    │
│ 6        ┆ 22    │
│ 7        ┆ 48    │
│ 8        ┆ 148   │
│ 9        ┆ 10    │
│ 10       ┆ 38    │
│ 11       ┆ 32    │
│ 12       ┆ 6     │
│ 13       ┆ 4     │
└──────────┴───────┘

In [5]:
df.head()

shape: (5, 10)
┌───────────┬───────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ letter_id ┆ id    ┆ title      ┆ pdf_pages  ┆ … ┆ chunk_id ┆ word_lengt ┆ full_markd ┆ embedding │
│ ---       ┆ ---   ┆ ---        ┆ ---        ┆   ┆ ---      ┆ h          ┆ own        ┆ ---       │
│ u32       ┆ u32   ┆ str        ┆ list[i64]  ┆   ┆ f64      ┆ ---        ┆ ---        ┆ list[f64] │
│           ┆       ┆            ┆            ┆   ┆          ┆ i64        ┆ str        ┆           │
╞═══════════╪═══════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 10000     ┆ 10000 ┆ CONTENANS  ┆ [4]        ┆ … ┆ 10000.0  ┆ 41         ┆            ┆ [-0.02758 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ 8,        │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ LES INTELL ┆ 0.020996, │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ IGENCES DE ┆ … -0.036… │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ CES ROY…   ┆           │
│ 10001     ┆ 10001 ┆ ET         ┆ [4, 5, …   ┆ … ┆ 10001.0  ┆ 1972       ┆            ┆ [-0.04687 │
│           ┆       ┆            ┆ 16]        ┆   ┆          ┆            ┆            ┆ 5, -0.020 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ DANS       ┆ 142, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ L'ITALIE   ┆ -0.00…    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ SEVLE, LES ┆           │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ INT…       ┆           │
│ 10001     ┆ 10001 ┆ ET         ┆ [4, 5, …   ┆ … ┆ 10001.1  ┆ 1660       ┆            ┆ [-0.04638 │
│           ┆       ┆            ┆ 16]        ┆   ┆          ┆            ┆            ┆ 7, -0.040 │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ DANS       ┆ 771, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ L'ITALIE   ┆ 0.015…    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ SEVLE, LES ┆           │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆ INT…       ┆           │
│ 10002     ┆ 10002 ┆ SVR LA     ┆ [16]       ┆ … ┆ 10002.0  ┆ 0          ┆            ┆ [-0.04858 │
│           ┆       ┆ PIECE      ┆            ┆   ┆          ┆            ┆            ┆ 4, -0.026 │
│           ┆       ┆ SVIVANTE,  ┆            ┆   ┆          ┆            ┆            ┆ 123, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ -0.03…    │
│ 10003     ┆ 10003 ┆ ET AVTRES  ┆ [16]       ┆ … ┆ 10003.0  ┆ 0          ┆            ┆ [-0.04858 │
│           ┆       ┆ DV PREMIER ┆            ┆   ┆          ┆            ┆            ┆ 4, -0.026 │
│           ┆       ┆ LIVRE      ┆            ┆   ┆          ┆            ┆            ┆ 123, …    │
│           ┆       ┆            ┆            ┆   ┆          ┆            ┆            ┆ -0.03…    │
└───────────┴───────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [9]:
soft

[[0, 13],
 [0],
 [3, 13],
 [1],
 [1],
 [12, 13],
 [9, 12, 13],
 [2],
 [4, 12, 13],
 [8, 12, 13],
 [4, 8, 13],
 [8, 13],
 [4, 8, 12],
 [13],
 [13],
 [13],
 [3, 5, 11],
 [11],
 [3],
 [3],
 [3],
 [4, 12, 13],
 [12],
 [0, 9, 13],
 [9, 12, 13],
 [12, 13],
 [9, 12, 13],
 [0, 9],
 [6, 9, 12],
 [9, 12, 13],
 [0, 9, 11],
 [0],
 [0, 12, 13],
 [13],
 [0, 4, 13],
 [0, 4, 13],
 [13],
 [9],
 [9],
 [5, 11, 12],
 [4, 12, 13],
 [9, 12, 13],
 [5, 12, 13],
 [5, 12, 13],
 [1],
 [9, 12],
 [9],
 [9],
 [5, 9, 11],
 [5, 9, 12],
 [9],
 [9],
 [9],
 [5, 11, 12],
 [8, 12, 13],
 [5, 11],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [12],
 [7],
 [12],
 [12],
 [5, 12, 13],
 [12, 13],
 [0, 9, 12],
 [0, 12, 13],
 [9, 12, 13],
 [0, 9, 12],
 [0, 9, 12],
 [9, 12],
 [0, 9, 12],
 [12],
 [12],
 [4, 13],
 [0],
 [0, 9, 12],
 [0, 9, 12],
 [12],
 [5, 6, 12],
 [12, 13],
 [9, 11, 12],
 [9, 12, 13],
 [0, 9, 13],
 [11],
 [5],
 [5],
 [13],
 [12, 13],
 [12],
 [0, 4, 12],
 [0],
 [5],
 [5, 11, 12],
 [5],
 [5],
 [5, 11, 12],
 [0, 5, 12],
 [10],
 [5, 11, 12],
 [12],
 [0, 4, 12],
 [0, 4, 12],
 [0, 12],
 [0, 4, 12],
 [12],
 [12, 13],
 [12],
 [12],
 [12],
 [12],
 [12],
 [4, 12, 13],
 [0],
 [0, 9, 12],
 [0, 5, 9],
 [0, 12],
 [0, 12, 13],
 [0, 12, 13],
 [0, 12, 13],
 [4, 12, 13],
 [0, 3, 12],
 [7, 12, 13],
 [4, 12, 13],
 [5, 11, 12],
 [11],
 [2],
 [8, 13],
 [8, 9, 13],
 [0, 8, 13],
 [5, 12],
 [7],
 [10],
 [6, 12],
 [2],
 [11],
 [13],
 [0],
 [6, 9, 12],
 [12],
 [9, 12, 13],
 [13],
 [12],
 [11],
 [0, 4, 12],
 [0, 12, 13],
 [1],
 [12],
 [0, 9, 12],
 [9, 12, 13],
 [13],
 [0, 9],
 [12],
 [0, 12, 13],
 [8, 12, 13],
 [0, 8, 13],
 [0, 8, 13],
 [8, 13],
 [8, 13],
 [0, 8, 13],
 [9, 12],
 [5, 12],
 [12],
 [0, 7, 13],
 [0, 9, 12],
 [8, 12],
 [8],
 [7],
 [4],
 [4, 12, 13],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [8],
 [7, 12, 13],
 [12, 13],
 [9, 12, 13],
 [6],
 [12, 13],
 [0, 12, 13],
 [13],
 [13],
 [12, 13],
 [9, 12, 13],
 [2],
 [8, 13],
 [10],
 [10],
 [9, 12],
 [12],
 [13],
 [12],
 [4],
 [0, 9, 13],
 [0, 4, 12],
 [9, 12, 13],
 [0, 12, 13],
 [6],
 [0, 12, 13],
 [4, 12],
 [4, 12, 13],
 [13],
 [9],
 [0, 9],
 [12],
 [5],
 [4],
 [4],
 [12],
 [12],
 [9, 12],
 [12],
 [4, 12, 13],
 [12],
 [4],
 [12, 13],
 [5, 12],
 [12],
 [9, 12],
 [4, 12],
 [4],
 [0, 9, 12],
 [7],
 [12, 13],
 [11, 12],
 [13],
 [12],
 [4, 8, 13],
 [12],
 [0, 4, 12],
 [5, 11, 12],
 [5],
 [6],
 [9, 12],
 [5, 12],
 [5, 11, 12],
 [9, 12, 13],
 [4, 12],
 [12],
 [0, 4, 12],
 [4],
 [9],
 [0, 9],
 [6, 9, 12],
 [0, 9, 12],
 [0, 6, 9],
 [1],
 [4, 12],
 [12],
 [5, 12],
 [5, 9, 12],
 [9, 12, 13],
 [9, 12],
 [12],
 [12, 13],
 [9, 12, 13],
 [4, 6, 12],
 [12],
 [12],
 [9, 12, 13],
 [6, 12, 13],
 [12],
 [5, 9, 12],
 [1],
 [9, 12],
 [1],
 [5, 9, 12],
 [12, 13],
 [8, 11, 12],
 [12],
 [9, 12, 13],
 [0, 9],
 [3, 7, 12],
 [6],
 [6, 12, 13],
 [1],
 [9, 12],
 [9, 12],
 [1],
 [12],
 [0, 9, 12],
 [9, 12, 13],
 [9, 12, 13],
 [12],
 [12],
 [12],
 [1],
 [9, 12, 13],
 [12],
 [12],
 [12],
 [10],
 [9],
 [6, 12],
 [12],
 [9, 12],
 [12],
 [9],
 [9, 12, 13],
 [6, 9, 12],
 [12],
 [0, 9, 12],
 [12],
 [9, 12],
 [0, 9, 12],
 [10],
 [0, 9, 12],
 [7, 8, 9],
 [1],
 [0, 6, 9],
 [5, 9, 12],
 [12],
 [12],
 [11],
 [12],
 [1],
 [12],
 [4, 6, 12],
 [0, 9, 12],
 [0, 9, 12],
 [10],
 [0, 6, 9],
 [1],
 [12],
 [11],
 [11],
 [1],
 [12],
 [12],
 [12],
 [3, 8, 11],
 [9, 12, 13],
 [4, 12, 13],
 [0, 5, 9],
 [9, 12, 13],
 [6, 9, 12],
 [0, 11, 12],
 [11],
 [4],
 [1],
 [0, 6, 12],
 [6],
 [4],
 [11],
 [5, 11],
 [1, 10],
 [0, 9],
 [11],
 [9, 12, 13],
 [9, 12, 13],
 [13],
 [11, 12, 13],
 [9],
 [11],
 [11],
 [11],
 [11],
 [6, 9, 12],
 [9, 12],
 [9],
 [11],
 [9],
 [9, 12, 13],
 [9],
 [9, 12],
 [9, 12],
 [0, 9, 13],
 [9, 12],
 [9],
 [9],
 [6, 9, 12],
 [0, 9],
 [0],
 [0, 9, 12],
 [9],
 [9],
 [4],
 [0, 9, 12],
 [9],
 [0, 9],
 [9],
 [9, 12, 13],
 [9],
 [10],
 [9, 12],
 [9],
 [9],
 [9],
 [9],
 [9],
 [1],
 [9, 12],
 [1],
 [9],
 [10],
 [9],
 [1],
 [0, 9, 12],
 [9],
 [9],
 [13]]

In [10]:
soft1

[[4],
 [8],
 [13],
 [2],
 [2],
 [1, 8, 11],
 [7, 8, 11],
 [0],
 [0, 8, 11],
 [7, 8, 11],
 [11],
 [11],
 [0, 8, 11],
 [13],
 [0, 11, 13],
 [0],
 [6, 10, 12],
 [6],
 [4, 7, 8],
 [3, 13],
 [6],
 [1, 8],
 [8],
 [1, 7, 8],
 [8],
 [3],
 [0, 8, 10],
 [7],
 [1, 7, 8],
 [0, 1, 10],
 [6, 7, 11],
 [1, 7, 11],
 [0, 1, 8],
 [0, 1, 8],
 [0, 1, 8],
 [7, 8, 11],
 [1, 7, 11],
 [7],
 [7, 10],
 [10],
 [0, 8, 11],
 [1, 7, 8],
 [1, 8, 10],
 [0, 4, 10],
 [2],
 [7, 8, 10],
 [7],
 [7],
 [5, 6, 13],
 [1, 7, 10],
 [7],
 [1, 7],
 [7],
 [6, 8, 10],
 [4, 8, 11],
 [5, 6, 10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [0, 8, 10],
 [0, 3, 10],
 [8],
 [10],
 [1, 8, 10],
 [1, 4, 8],
 [1, 7, 8],
 [0, 8],
 [1, 8],
 [1, 7, 8],
 [1],
 [1, 7, 8],
 [1, 8],
 [5, 8, 10],
 [1, 8],
 [0, 1, 3],
 [1, 7, 8],
 [1, 7, 8],
 [1, 7, 8],
 [8, 10],
 [1, 8, 10],
 [0, 8],
 [6, 7, 8],
 [7, 8, 11],
 [1, 7, 8],
 [6],
 [10],
 [10],
 [0, 3, 11],
 [4, 8],
 [8],
 [1, 8],
 [1, 7, 8],
 [10],
 [5],
 [10],
 [5],
 [5],
 [1, 6, 10],
 [2, 9],
 [5, 6, 10],
 [1, 8, 10],
 [8],
 [8],
 [8],
 [8],
 [8],
 [0, 3, 8],
 [0, 8, 11],
 [7, 8, 10],
 [1, 8, 10],
 [8],
 [8],
 [0],
 [1, 7, 8],
 [7],
 [0, 7, 10],
 [8],
 [1, 4, 8],
 [1, 4, 8],
 [3, 8, 11],
 [0, 8, 11],
 [0, 6, 8],
 [0, 8],
 [0],
 [1, 6, 10],
 [6],
 [0, 10, 11],
 [7, 8, 11],
 [0, 7, 11],
 [11],
 [10],
 [0, 1, 3],
 [9],
 [1],
 [0, 10],
 [6],
 [3],
 [0, 1, 8],
 [1, 8],
 [8],
 [8],
 [4, 8, 13],
 [8],
 [6],
 [8],
 [1, 8],
 [2],
 [1, 8],
 [7, 8],
 [8],
 [4, 8, 11],
 [7],
 [8],
 [0],
 [0, 11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [8],
 [5, 10],
 [1, 8],
 [3],
 [1, 7, 8],
 [1, 8, 11],
 [11],
 [0],
 [0, 11],
 [0],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [11],
 [0],
 [8],
 [1, 7, 8],
 [1],
 [0, 3, 4],
 [8],
 [3, 4, 8],
 [4, 8, 13],
 [4, 8, 11],
 [1, 7, 8],
 [13],
 [0, 11, 13],
 [9],
 [9],
 [8],
 [1, 8],
 [3],
 [8],
 [0, 8],
 [1, 7, 8],
 [8],
 [1, 7, 8],
 [0, 8, 10],
 [1],
 [1, 8],
 [0, 1, 8],
 [8, 11],
 [3],
 [1, 7, 8],
 [1, 7, 8],
 [1, 8],
 [10],
 [0, 8],
 [0, 8, 11],
 [8],
 [1, 8],
 [1, 4, 8],
 [0, 1, 8],
 [0, 8],
 [1, 8],
 [8],
 [1, 4, 8],
 [10],
 [8],
 [1, 7, 8],
 [0, 8],
 [0, 8, 11],
 [8],
 [3],
 [4],
 [5],
 [4],
 [8],
 [0, 11],
 [0, 8, 10],
 [0, 1, 8],
 [6, 7, 10],
 [10],
 [1],
 [1, 7, 8],
 [10],
 [5],
 [7, 8, 11],
 [1, 4, 8],
 [0, 1, 8],
 [0],
 [0, 1, 8],
 [1, 7, 8],
 [1, 7],
 [1],
 [1, 8],
 [1],
 [2],
 [0, 8],
 [1, 8],
 [10],
 [1, 8, 10],
 [8],
 [1, 7, 8],
 [8],
 [0, 3, 8],
 [4],
 [0, 1, 12],
 [8],
 [8, 10],
 [1, 4, 8],
 [1, 8],
 [8],
 [10],
 [2],
 [8],
 [2],
 [1, 8, 10],
 [4],
 [6, 7, 8],
 [8],
 [1, 7, 8],
 [1, 7],
 [5, 6, 8],
 [1],
 [1, 4, 8],
 [2],
 [1, 7, 8],
 [1, 7, 8],
 [2],
 [1, 8, 10],
 [1, 7],
 [8],
 [1, 7, 8],
 [1, 8],
 [8],
 [8],
 [2],
 [1, 7, 8],
 [8],
 [1, 8],
 [8],
 [9],
 [7],
 [1],
 [1, 8, 10],
 [1, 7, 8],
 [8],
 [1, 7, 8],
 [1, 8, 11],
 [1],
 [8],
 [8],
 [8],
 [1, 7, 8],
 [8],
 [9],
 [1, 7, 8],
 [12],
 [2, 9],
 [1, 7, 12],
 [7, 10],
 [1, 8, 10],
 [5, 8, 10],
 [6],
 [8],
 [2],
 [8],
 [0, 1, 8],
 [1, 7, 8],
 [1, 7, 8],
 [9],
 [1],
 [2],
 [7, 8, 10],
 [6],
 [6],
 [2],
 [8],
 [1, 8],
 [8],
 [0, 6, 11],
 [8],
 [0, 8, 13],
 [7, 8, 10],
 [1, 7, 8],
 [5, 8, 12],
 [5],
 [6],
 [0],
 [2],
 [5, 8],
 [5],
 [8],
 [6, 10],
 [6, 10],
 [2, 9],
 [1, 7, 8],
 [6],
 [1, 7, 8],
 [1, 7, 8],
 [8, 11, 13],
 [6],
 [7, 8],
 [6],
 [6],
 [6],
 [6],
 [1],
 [1, 7, 8],
 [7],
 [6],
 [1, 7],
 [4, 7, 8],
 [7, 8],
 [7, 8],
 [8],
 [12],
 [1, 7, 8],
 [7],
 [7],
 [1, 8],
 [1, 7, 8],
 [7, 8],
 [12],
 [1, 7, 8],
 [1, 7, 8],
 [0, 7, 8],
 [12],
 [7],
 [7],
 [7],
 [1, 4, 10],
 [7],
 [9],
 [1, 7, 8],
 [7],
 [7],
 [7],
 [7],
 [7],
 [2],
 [1, 7, 8],
 [2],
 [1, 7],
 [9],
 [7],
 [2],
 [1, 7, 8],
 [4, 7, 8],
 [1, 7, 8],
 [4]]

In [7]:
from clustering.clustering import create_cluster
import polars as pl

folder = "ribier_v1"

df1 = pl.read_parquet(f"./books_work/{folder}/data/{folder}_chunked.parquet")
docs = df1["embedding"].to_list()
cluster3, soft3, samples3, iters3 = create_cluster(docs, run_num=1, soft_assign=False)
cluster4, soft4, samples4, iters4 = create_cluster(docs, run_num=2, soft_assign=False)
df1 = df1.with_columns(cluster3=pl.Series(cluster3), cluster4=pl.Series(cluster4))
print("Cluster 3:")
with pl.Config(tbl_rows=25):
    display(df1["cluster3"].value_counts().sort("cluster3"))
print("Cluster 4:")
with pl.Config(tbl_rows=25):
    display(df1["cluster4"].value_counts().sort("cluster4"))

  Estimated number of clusters: 14
  Restart 1/10 (seed 10) — score: 0.9402
  Restart 2/10 (seed 11) — score: 0.9400
  Restart 3/10 (seed 12) — score: 0.9403
  Restart 4/10 (seed 13) — score: 0.9403
  Restart 5/10 (seed 14) — score: 0.9398
  Restart 6/10 (seed 15) — score: 0.9402
  Restart 7/10 (seed 16) — score: 0.9404
  Restart 8/10 (seed 17) — score: 0.9399
  Restart 9/10 (seed 18) — score: 0.9401
  Restart 10/10 (seed 19) — score: 0.9393
  Best score: 0.9404
  Estimated number of clusters: 14
  Restart 1/10 (seed 20) — score: 0.9406
  Restart 2/10 (seed 21) — score: 0.9400
  Restart 3/10 (seed 22) — score: 0.9396
  Restart 4/10 (seed 23) — score: 0.9399
  Restart 5/10 (seed 24) — score: 0.9401
  Restart 6/10 (seed 25) — score: 0.9394
  Restart 7/10 (seed 26) — score: 0.9403
  Restart 8/10 (seed 27) — score: 0.9402
  Restart 9/10 (seed 28) — score: 0.9386
  Restart 10/10 (seed 29) — score: 0.9399
  Best score: 0.9406
Cluster 3:

shape: (14, 2)
┌──────────┬───────┐
│ cluster3 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 75    │
│ 1        ┆ 21    │
│ 2        ┆ 17    │
│ 3        ┆ 78    │
│ 4        ┆ 6     │
│ 5        ┆ 26    │
│ 6        ┆ 23    │
│ 7        ┆ 9     │
│ 8        ┆ 3     │
│ 9        ┆ 28    │
│ 10       ┆ 42    │
│ 11       ┆ 54    │
│ 12       ┆ 24    │
│ 13       ┆ 7     │
└──────────┴───────┘

Cluster 4:

shape: (14, 2)
┌──────────┬───────┐
│ cluster4 ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 28    │
│ 1        ┆ 65    │
│ 2        ┆ 19    │
│ 3        ┆ 9     │
│ 4        ┆ 23    │
│ 5        ┆ 6     │
│ 6        ┆ 37    │
│ 7        ┆ 68    │
│ 8        ┆ 11    │
│ 9        ┆ 78    │
│ 10       ┆ 8     │
│ 11       ┆ 14    │
│ 12       ┆ 25    │
│ 13       ┆ 22    │
└──────────┴───────┘